### PR TITLE
Add mobile search endpoint to Tahoe

### PR DESCRIPTION
**Pull request by melvinsoft**
## Description Edited

This is cherry-pick from [Omar's Upstream PR](https://github.com/edx/edx-platform/pull/16757), to introduce mobile search in Tahoe. Please check the description.

## Endpoint description

```
**Use Cases**

        Request information on all courses visible to the specified user.

    **Example Requests**

        GET /api/courses/v1/courses/

    **Response Values**

        Body comprises a list of objects as returned by `CourseDetailView`.

    **Parameters**
        search_term (optional):
            Search term to filter courses (used by ElasticSearch).

        username (optional):
            The username of the specified user whose visible courses we
            want to see. The username is not required only if the API is
            requested by an Anonymous user.

        org (optional):
            If specified, visible `CourseOverview` objects are filtered
            such that only those belonging to the organization with the
            provided org code (e.g., "HarvardX") are returned.
            Case-insensitive.

        mobile (optional):
            If specified, only visible `CourseOverview` objects that are
            designated as mobile_available are returned.

    **Returns**

        * 200 on success, with a list of course discovery objects as returned
          by `CourseDetailView`.
        * 400 if an invalid parameter was sent or the username was not provided
          for an authenticated request.
        * 403 if a user who does not have permission to masquerade as
          another user specifies a username other than their own.
        * 404 if the specified user does not exist, or the requesting user does
          not have permission to view their courses.

        Example response:

            [
              {
                "blocks_url": "/api/courses/v1/blocks/?course_id=edX%2Fexample%2F2012_Fall",
                "media": {
                  "course_image": {
                    "uri": "/c4x/edX/example/asset/just_a_test.jpg",
                    "name": "Course Image"
                  }
                },
                "description": "An example course.",
                "end": "2015-09-19T18:00:00Z",
                "enrollment_end": "2015-07-15T00:00:00Z",
                "enrollment_start": "2015-06-15T00:00:00Z",
                "course_id": "edX/example/2012_Fall",
                "name": "Example Course",
                "number": "example",
                "org": "edX",
                "start": "2015-07-17T12:00:00Z",
                "start_display": "July 17, 2015",
                "start_type": "timestamp"
              }
            ]
```

### CODE REVIEW

**Comment by melvinsoft** [comment]
@OmarIthawi @bezidejni I've reverted the previous cherry pick, and cherry picked Omar's upstream PR. Please take a new look.

**Comment by bryanlandia** [comment]
@melvinsoft I think this might be ready to merge.

**Comment by melvinsoft** [comment]
@OmarIthawi @bezidejni Thanks for your reviews! Tests aren't working in Tahoe ATM, but I'll make sure to run them as soon as they're fixed.

@bryanlandia Thanks for the reminder!

**Comment by jaimeohm** [comment]
Oh noes... it doesn't work! I've attached some helpful screenshots. cc @melvinsoft @OmarIthawi 

Here's a screenshot of the iOS app's request working against Starbucks Production with "/appsembler_api/v0/search_courses" as the COURSE_SEARCH_URL string. This returns a 200 and a course list:

screen shot 2018-10-15 at 8 24 19 pm

Here's a screenshot of the app's request failing against Tahoe Staging with "api/courses/v1/courses" as the COURSE_SEARCH_URL string, it returns a 301 redirect:

screen shot 2018-10-15 at 8 59 55 pm

Here's a screenshot of the app's request failing against Tahoe Staging with "api/courses/v1/courses" as the COURSE_SEARCH_URL string, it looks like it's redirected to an invalid URL and also gets a 403 forbidden error:

screen shot 2018-10-15 at 8 59 33 pm

I tried changing the URL to the seemingly invalid one "api/courses/v1/courses/" that the redirect seems to point to and I get no error, but also no returned courses:

screen shot 2018-10-15 at 8 15 48 pm

cc @thraxil it's not ready for production

**Comment by OmarIthawi** [comment]
Thanks @jaimeohm for reporting the bug.

Could you please provide us with the a `curl` command that fails? This helps a lot to reproduce the error and getting it fixed.

**Comment by jaimeohm** [comment]
@OmarIthawi Unfortunately, I didn't use a curl command, so I cannot give that to you. These screenshots are from my proxy server that I run when deep debugging the mobile app communications. The top half in each screenshot is the request-to-the-server information, which should help you create a curl request, and the bottom half is the server's response.

**Comment by OmarIthawi** [comment]
@jaimeohm it's ok. It turns out that no `curl` is needed since it's possible to actually see the URLs in the browser:

 - https://mobile-demo-company.staging-tahoe.appsembler.com/api/courses/v1/courses?mobile=true&page=1&page_size=20&search_term=jaime
- Doesn't work: It needs a redirect, and no course was found with `jaime`

So I modified it a bit by: adding the trailing slash, removing `mobile=true` and changed the search term to `Android`:
  - https://mobile-demo-company.staging-tahoe.appsembler.com/api/courses/v1/courses/?page=1&page_size=20&search_term=android
 - It's working fine.

So here's what I think:

 - Create a `mobile` course with the proper advanced settings for it to be declared as mobile friendly
 - Put the word `jaime` in it somewhere in the title
 - Add the trailing `/` to the URL after `courses`

It should work.

Please let me know how it goes.

cc: @melvinsoft @thraxil

**Comment by jaimeohm** [comment]
@melvinsoft @thraxil It works!!! Woot woo!!! Can you let me know when this will go live on production?

Thank you for your help @OmarIthawi

**Comment by melvinsoft** [comment]
@OmarIthawi Thanks for helping @jaimeohm to troubleshoot this! @jaimeohm thanks for trying it out!

**Pull request merged**
