### PR TITLE
added logic to display correct button caption

### PR DESCRIPTION
**Pull request by mbifulco**
This might be a candidate for a proper PR at some point back to the folks at EdX, too.  I'll have to look into that.

### CODE REVIEW

**Comment by tkeemon** [comment]
Funny coincidence: I just got a support request from a customer asking for this bugfix. It's probably be appreciated upstream.

**Comment by mbifulco** [comment]
FYI @tkeemon: https://github.com/edx/edx-platform/pull/9703

**Comment by tkeemon** [comment]
Do you want me to wait on the edx PR to get accepted, then pull that in instead of this PR?

Let me know what you prefer.

**Comment by mbifulco** [comment]
@tkeemon at this point my code should be identical to EdX-platform's code anyway - I think you can pull this down without a problem.

**Comment by tkeemon** [comment]
Great. This works perfectly.

**Pull request merged**
