### PR TITLE
Appsembler/ficus/feature/account settings extension fields

### PR DESCRIPTION
**Pull request by amirtds**

### CODE REVIEW

**Comment by thraxil** [comment]
Can one of the admins verify this patch?

**Comment by thraxil** [comment]
Can one of the admins verify this patch?

**Comment by amirtds** [comment]
Hey @thraxil i'm using this PR for testing some account extension feature in my develop branch , it doesn't affect any prod client

**Comment by thraxil** [comment]
sorry. those comments are from the jenkins setup that i'm working on. not done setting it up yet.

**Pull request closed without merging**
