### PR TITLE
Use our forked analytics-python

### PR DESCRIPTION
**Pull request by shadinaif**
## Change description

Use our forked analytics-python

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

https://appsembler.atlassian.net/browse/RED-2969

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Review by OmarIthawi — COMMENTED** [review]
this is a big change, could you please open a upstream pull request and explain why do you think this is a bug? I know that we've already forked the repo but the change isn't trivial to test or review.

This change seems very dangerous since it touches threading/multiprocessing
think about: servers going out of memory, site data leaks or bringing servers down.
such changes actually shouldn't be done without consulting with the package maintainers in my opinion.
i.e. I'd rather accept the bug and wait for a couple of months to ensure we did the right thing instead of potentially hurting our production instances.

**Review by OmarIthawi — CHANGES_REQUESTED** [review]
first of all, thanks for getting to the bottom of this bug.


this is a big change, could you please open a upstream pull request and explain why do you think this is a bug? I know that we've already forked the repo but the change isn't trivial to test or review.

This change seems very dangerous since it touches threading/multiprocessing
think about: servers going out of memory, site data leaks or bringing servers down.
such changes actually shouldn't be done without consulting with the package maintainers in my opinion.
i.e. I'd rather accept the bug and wait for a couple of months to ensure we did the right thing instead of potentially hurting our production instances.

**Comment by OmarIthawi** [comment]
in other words @shadinaif. I don't understand well the changes done https://github.com/appsembler/analytics-python/pull/2 . it seems too good to be true it raises a red-flag because we don't really know the implication of the change.

**Comment by OmarIthawi** [comment]
I'm not angry, I'm just trying to scrap my head about the change. Please check the links below becasue I think we have a sync_mode which skips queueing:

 - https://github.com/segmentio/analytics-python/pull/147
 - https://github.com/segmentio/analytics-python/issues/101
 - [search results for "celery" in `segmentio/analytics-python`](https://github.com/segmentio/analytics-python/search?q=celery&type=issues)

**Comment by shadinaif** [comment]
Thank you @OmarIthawi !

Processes are created anyway by Celery with or without the fix. The problem is that this is not compatible with normal queues. `JoinableQueue` uses semaphores, I can't think of a data leak scenario because of that. And I don't think the server can run out of memory because of semaphores. But of course, I'm not saying this is guaranteed, we should bring it into action to verify it

When Celery forks the process; the queue in the thread is duplicated because it's a Python thread, not a real thread. `JoinableQueue` will guarantee queue object sharing

On the other hand, the problem with `sync_mode` is that it sends to segment directly with every single log. Blocking execution until sent, no thread is created, and also not batching logs at all

What should we do?
* take the possible risk?
* accept the `sync_mode` implications?
* do some changes to make Celery work with `sync_mode` but not `edx-platform`?
* accept the bug as unresolvable?

**Comment by OmarIthawi** [comment]
> Thank you @OmarIthawi !
> 
> Processes are created anyway by Celery with or without the fix. The problem is that this is not compatible with normal queues. `JoinableQueue` uses semaphores, I can't think of a data leak scenario because of that. And I don't think the server can run out of memory because of semaphores. But of course, I'm not saying this is guaranteed, we should bring it into action to verify it
> 
> When Celery forks the process; the queue in the thread is duplicated because it's a Python thread, not a real thread. `JoinableQueue` will guarantee queue object sharing
> 
> On the other hand, the problem with `sync_mode` is that it sends to segment directly with every single log. Blocking execution until sent, no thread is created, and also not batching logs at all
> 
> What should we do?
> 
> * take the possible risk?
> * accept the `sync_mode` implications?
> * do some changes to make Celery work with `sync_mode` but not `edx-platform`?
> * accept the bug as unresolvable?


> * accept the `sync_mode` implications?

The `sync_mode` makes total sense in celery and command line. To oversimplify the solution, we'd need the following form of client:

```py
default_client = Client(write_key, ..., sync_mode=bool(settings.IS_CELERY))
```

or using a `@task_postrun.connect` like we did for honeycomb:

https://github.com/appsembler/edx-platform/blob/9baaffbf75af52c8f40a54d8da3413e63805771c/lms/celery.py#L71-L74

the idea is to clear the segment queue after each task run instead of `never`, this would work exactly like `sync_mode` but it may be easier to implement.

**Comment by bryanlandia** [comment]
@shadinaif @OmarIthawi Maybe a workaround to consider is to make an upstream PR to Segment, and in the meantime change our Celery config so that the queue used for any task that will generate an event via a worker not use multiple processes.  I believe the only ones that do are PersistentGrade calculation and the Completion Aggregator tasks.  We could create a new queue just for them and only allow 1 process.

Correct me if I'm wrong, but I believe it's the `concurrency` setting that controls the number of processes spawned.  Right now, the default queue can have up to 8 processes!

https://github.com/appsembler/edx-configs/blob/master/appsembler/tahoe/us/juniper/prod/files/server-vars.yml#L350-L355

```yaml
EDXAPP_CELERY_WORKERS:
    service_variant: lms
    concurrency: 8
    monitor: true
    prefetch_optimization: fair
    max_tasks_per_child: 1000
```
(abbreviated)

**Comment by shadinaif** [comment]
Closed in favour of https://github.com/appsembler/edx-platform/pull/1175

**Pull request closed without merging**
