### PR TITLE
Pull Jenkinsfile into ficus

### PR DESCRIPTION
**Pull request by thraxil**
OK. Here's our basic Jenkins setup for the ficus branch.

We're still skipping a lot of tests, but it's a start.

### CODE REVIEW

**Comment by thraxil** [comment]
OK, looks like there are two tests failing that will have to be dealt with. The first is i8n related:

```
[test_lib_all] ========================================
[test_lib_all]  Running tests for pavelib/paver_tests 
[test_lib_all] ========================================
[test_lib_all] [39;49;00m.......................F....
[test_lib_all] This test tests that i18n extraction (`paver i18n_extract`) works properly. If you experience failures, please check that all instances of `gettext` and `ngettext` are used correctly. You can also try running `paver i18n_extract -v` locally for more detail.
[test_lib_all] 
[test_lib_all] Extracting i18n strings and generating dummy translations; this may take a few minutes
[test_lib_all] E......................................................................................................................................
[test_lib_all] ======================================================================
[test_lib_all] ERROR: test suite for <class 'pavelib.paver_tests.test_extract_and_generate.TestGenerate'>
[test_lib_all] ----------------------------------------------------------------------
[test_lib_all] Traceback (most recent call last):
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
[test_lib_all]     self.setUp()
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
[test_lib_all]     self.setupContext(ancestor)
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
[test_lib_all]     try_run(context, names)
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
[test_lib_all]     return func()
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/pavelib/paver_tests/test_extract_and_generate.py", line 44, in setUpClass
[test_lib_all]     extract.main(verbose=0)
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/i18n/__init__.py", line 51, in __call__
[test_lib_all]     return self.run(args)
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/i18n/extract.py", line 126, in run
[test_lib_all]     execute(make_django_cmd, working_directory=configuration.root_dir, stderr=stderr)
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/i18n/execute.py", line 21, in execute
[test_lib_all]     sp.check_call(command, cwd=working_directory, stderr=stderr, shell=True)
[test_lib_all]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
[test_lib_all]     raise CalledProcessError(retcode, cmd)
[test_lib_all] CalledProcessError: Command 'django-admin.py makemessages -l en -v0 --ignore="common/static/xmodule/modules/*" --ignore="common/static/xmodule/descriptors/*" --ignore="*/migrations/*" --ignore="node_modules/*" --ignore="conf/*" --ignore="docs/*" --ignore="*/fonts/*" --ignore="*/img/*" --ignore="*/images/*" --ignore="*/sass/*" --ignore="*/css/*" --ignore="common/test/*" --ignore="test_root/*" --ignore="*/terrain/*" --ignore="*/spec/*" --ignore="*/tests/*" --ignore="*/features/*" --ignore="lms/static/js/i18n/*" --ignore="cms/static/js/i18n/*" -d django' returned non-zero exit status 1
[test_lib_all] -------------------- >> begin captured logging << --------------------
[test_lib_all] i18n.execute: INFO: Executing in . ...
[test_lib_all] i18n.execute: INFO: pybabel -q extract --mapping=conf/locale/babel_mako.cfg --add-comments="Translators:" --keyword="interpolate" . --output=conf/locale/en/LC_MESSAGES/mako.po
[test_lib_all] i18n.execute: INFO: Executing in . ...
[test_lib_all] i18n.execute: INFO: pybabel -q extract --mapping=conf/locale/babel_underscore.cfg --add-comments="Translators:" --keyword="interpolate" . --output=conf/locale/en/LC_MESSAGES/underscore.po
[test_lib_all] i18n.execute: INFO: Executing in . ...
[test_lib_all] i18n.execute: INFO: django-admin.py makemessages -l en -v0 --ignore="common/static/xmodule/modules/*" --ignore="common/static/xmodule/descriptors/*" --ignore="*/migrations/*" --ignore="node_modules/*" --ignore="conf/*" --ignore="docs/*" --ignore="*/fonts/*" --ignore="*/img/*" --ignore="*/images/*" --ignore="*/sass/*" --ignore="*/css/*" --ignore="common/test/*" --ignore="test_root/*" --ignore="*/terrain/*" --ignore="*/spec/*" --ignore="*/tests/*" --ignore="*/features/*" --ignore="lms/static/js/i18n/*" --ignore="cms/static/js/i18n/*" -d django
[test_lib_all] --------------------- >> end captured logging << ---------------------
```

So maybe we broke a translation file somewhere?

Second one is something to do with SASS and paver's expectations of which directories are involved:

```
[test_lib_all] ======================================================================
[test_lib_all] FAIL: test_watch_theme_assets (pavelib.paver_tests.test_assets.TestPaverWatchAssetTasks)
[test_lib_all] ----------------------------------------------------------------------
[test_lib_all] Traceback (most recent call last):
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/pavelib/paver_tests/test_assets.py", line 205, in test_watch_theme_assets
[test_lib_all]     self.assertItemsEqual(sass_watcher_args[1], self.expected_sass_directories)
[test_lib_all] AssertionError: Element counts were not equal:
[test_lib_all] First has 1, Second has 0:  Path(u'/home/jenkins/workspace/edx-platform/common/test/test-theme/customer_specific/cms/static/sass')
[test_lib_all] First has 1, Second has 0:  Path(u'/home/jenkins/workspace/edx-platform/common/test/test-theme/customer_specific/lms/static/sass')
[test_lib_all] -------------------- >> begin captured stdout << ---------------------
[test_lib_all] ---> pavelib.assets.watch_assets
[test_lib_all] DINAMO: /home/jenkins/workspace/edx-platform/common/test/test-theme/customer_specific/lms/static/sass
[test_lib_all] DINAMO: /home/jenkins/workspace/edx-platform/common/test/test-theme/customer_specific/cms/static/sass
[test_lib_all] find /home/jenkins/workspace/edx-platform/lms /home/jenkins/workspace/edx-platform/cms /home/jenkins/workspace/edx-platform/common -type f -name "*.coffee"
[test_lib_all] Starting asset watcher...
[test_lib_all] 
[test_lib_all] --------------------- >> end captured stdout << ----------------------
```

**Comment by thraxil** [comment]
Also hundreds of pep8 violations:

```
pep8 . | tee /home/jenkins/workspace/edx-platform/reports/pep8/pep8.report -a



Build failed running pavelib.quality.run_pep8: Too many pep8 violations. Number of pep8 violations: 114



Violations:

./cms/djangoapps/search_api/api.py:6:1: E302 expected 2 blank lines, found 1

./cms/djangoapps/search_api/api.py:9:5: E101 indentation contains mixed spaces and tabs

./cms/djangoapps/search_api/api.py:9:5: W191 indentation contains tabs

./cms/djangoapps/search_api/api.py:10:5: E101 indentation contains mixed spaces and tabs

./cms/djangoapps/search_api/api.py:10:5: W191 indentation contains tabs

./cms/djangoapps/search_api/api.py:11:5: E101 indentation contains mixed spaces and tabs

./cms/djangoapps/search_api/api.py:11:5: W191 indentation contains tabs

./cms/djangoapps/search_api/api.py:14:5: E101 indentation contains mixed spaces and tabs

./cms/djangoapps/search_api/api.py:14:5: W191 indentation contains tabs

./cms/djangoapps/search_api/api.py:14:44: W291 trailing whitespace

./cms/djangoapps/search_api/api.py:15:5: E101 indentation contains mixed spaces and tabs

./cms/djangoapps/search_api/api.py:15:5: W191 indentation contains tabs

./cms/djangoapps/search_api/api.py:23:1: E101 indentation contains mixed spaces and tabs

./cms/djangoapps/search_api/api.py:23:1: W191 indentation contains tabs

./cms/djangoapps/search_api/api.py:24:1: W191 indentation contains tabs

./cms/djangoapps/search_api/api.py:24:2: E101 indentation contains mixed spaces and tabs

./cms/djangoapps/search_api/api.py:24:7: E128 continuation line under-indented for visual indent

./cms/djangoapps/search_api/permissions.py:10:64: W292 no newline at end of file

./cms/djangoapps/search_api/views.py:4:33: W291 trailing whitespace

./cms/djangoapps/search_api/views.py:28:31: W291 trailing whitespace

./cms/djangoapps/search_api/views.py:32:1: E302 expected 2 blank lines, found 1

./cms/djangoapps/search_api/views.py:39:27: E201 whitespace after '('

./cms/djangoapps/search_api/views.py:40:5: E301 expected 1 blank line, found 0

./cms/djangoapps/search_api/views.py:43:13: E123 closing bracket does not match indentation of opening bracket's line

./cms/djangoapps/search_api/views.py:53:27: E201 whitespace after '('

./cms/djangoapps/search_api/views.py:54:1: W293 blank line contains whitespace

./cms/djangoapps/search_api/views.py:58:13: E123 closing bracket does not match indentation of opening bracket's line

./cms/djangoapps/search_api/views.py:86:21: E126 continuation line over-indented for hanging indent

./cms/djangoapps/search_api/views.py:89:17: E121 continuation line under-indented for hanging indent

./cms/djangoapps/contentstore/courseware_index.py:33:20: E231 missing whitespace after ','

./cms/envs/aws_appsembler.py:47:1: E124 closing bracket does not match visual indentation

./cms/envs/aws_appsembler.py:76:5: E124 closing bracket does not match visual indentation

./cms/envs/devstack_appsembler.py:28:1: E124 closing bracket does not match visual indentation

./cms/envs/devstack_appsembler.py:65:5: E124 closing bracket does not match visual indentation

./pavelib/servers.py:150:1: E302 expected 2 blank lines, found 1

./pavelib/servers.py:163:1: E302 expected 2 blank lines, found 1

./lms/urls.py:972:21: W291 trailing whitespace

./lms/djangoapps/courseware/views/views.py:121:1: E303 too many blank lines (4)

./lms/djangoapps/courseware/views/views.py:163:58: E201 whitespace after '{'

./lms/djangoapps/courseware/views/views.py:163:77: E202 whitespace before '}'

./lms/djangoapps/courseware/views/views.py:700:14: W291 trailing whitespace

./lms/djangoapps/badges/models.py:63:22: E251 unexpected spaces around keyword / parameter equals

./lms/djangoapps/badges/models.py:63:24: E251 unexpected spaces around keyword / parameter equals

./lms/djangoapps/badges/events/course_meta.py:79:55: W291 trailing whitespace

./lms/djangoapps/badges/events/course_meta.py:95:1: W391 blank line at end of file

./lms/djangoapps/branding/decorators.py:8:1: E302 expected 2 blank lines, found 1

./lms/djangoapps/branding/decorators.py:24:28: W292 no newline at end of file

./lms/djangoapps/student_account/fields.py:17:26: W291 trailing whitespace

./lms/djangoapps/student_account/fields.py:58:64: W291 trailing whitespace

./lms/djangoapps/student_account/fields.py:68:34: W291 trailing whitespace

./lms/djangoapps/student_account/fields.py:73:72: W291 trailing whitespace

./lms/djangoapps/student_account/fields.py:75:12: W291 trailing whitespace

./lms/djangoapps/student_account/fields.py:82:58: W291 trailing whitespace

./lms/djangoapps/student_account/fields.py:87:1: W391 blank line at end of file

./lms/djangoapps/student_account/views.py:537:1: W293 blank line contains whitespace

./lms/djangoapps/student_account/views.py:543:73: W291 trailing whitespace

./lms/djangoapps/student_account/views.py:563:26: W291 trailing whitespace

./lms/djangoapps/student_account/views.py:566:14: W291 trailing whitespace

./lms/djangoapps/appsembler_api/serializers.py:10:1: E302 expected 2 blank lines, found 1

./lms/djangoapps/appsembler_api/urls.py:30:1: W391 blank line at end of file

./lms/djangoapps/appsembler_api/utils.py:13:1: E302 expected 2 blank lines, found 1

./lms/djangoapps/appsembler_api/utils.py:27:92: E231 missing whitespace after ','

./lms/djangoapps/appsembler_api/utils.py:42:9: E124 closing bracket does not match visual indentation

./lms/djangoapps/appsembler_api/utils.py:45:21: W292 no newline at end of file

./lms/djangoapps/appsembler_api/views.py:70:5: E303 too many blank lines (2)

./lms/djangoapps/appsembler_api/views.py:123:49: E202 whitespace before '}'

./lms/djangoapps/appsembler_api/views.py:132:5: E303 too many blank lines (2)

./lms/djangoapps/appsembler_api/views.py:146:9: E303 too many blank lines (2)

./lms/djangoapps/appsembler_api/views.py:156:32: E126 continuation line over-indented for hanging indent

./lms/djangoapps/appsembler_api/views.py:227:29: E122 continuation line missing indentation or outdented

./lms/djangoapps/appsembler_api/views.py:349:17: E123 closing bracket does not match indentation of opening bracket's line

./lms/djangoapps/appsembler_api/views.py:350:13: E124 closing bracket does not match visual indentation

./lms/djangoapps/appsembler_api/views.py:384:30: E126 continuation line over-indented for hanging indent

./lms/djangoapps/appsembler_api/views.py:412:30: E126 continuation line over-indented for hanging indent

./lms/djangoapps/appsembler_api/views.py:450:30: E126 continuation line over-indented for hanging indent

./lms/djangoapps/appsembler_api/views.py:728:22: E225 missing whitespace around operator

./lms/envs/appsembler.py:7:41: E262 inline comment should start with '# '

./lms/envs/appsembler.py:26:35: E202 whitespace before ')'

./lms/envs/aws_appsembler.py:74:1: E124 closing bracket does not match visual indentation

./lms/envs/aws_appsembler.py:103:5: E124 closing bracket does not match visual indentation

./lms/envs/devstack_appsembler.py:68:1: E124 closing bracket does not match visual indentation

./lms/envs/devstack_appsembler.py:105:5: E124 closing bracket does not match visual indentation

./lms/envs/devstack_appsembler.py:133:5: W291 trailing whitespace

./openedx/core/djangoapps/user_api/views.py:47:1: E302 expected 2 blank lines, found 1

./openedx/core/djangoapps/appsembler/external_courses/admin.py:5:1: E302 expected 2 blank lines, found 1

./openedx/core/djangoapps/appsembler/external_courses/admin.py:12:5: E303 too many blank lines (2)

./openedx/core/djangoapps/appsembler/external_courses/admin.py:15:1: W391 blank line at end of file

./openedx/core/djangoapps/appsembler/external_courses/models.py:6:1: E302 expected 2 blank lines, found 1

./openedx/core/djangoapps/appsembler/external_courses/tasks.py:19:1: E302 expected 2 blank lines, found 1

./openedx/core/djangoapps/appsembler/external_courses/tasks.py:50:24: E251 unexpected spaces around keyword / parameter equals

./openedx/core/djangoapps/appsembler/external_courses/tasks.py:50:26: E251 unexpected spaces around keyword / parameter equals

./openedx/core/djangoapps/appsembler/external_courses/tasks.py:51:27: E251 unexpected spaces around keyword / parameter equals

./openedx/core/djangoapps/appsembler/external_courses/tasks.py:51:29: E251 unexpected spaces around keyword / parameter equals

./openedx/core/djangoapps/appsembler/external_courses/tasks.py:79:71: E261 at least two spaces before inline comment

./openedx/core/djangoapps/appsembler/external_courses/tasks.py:118:1: E303 too many blank lines (3)

./openedx/core/djangoapps/appsembler/external_courses/management/commands/fetch_external_courses.py:11:1: E302 expected 2 blank lines, found 1

./openedx/core/djangoapps/appsembler/external_courses/management/commands/fetch_external_courses.py:41:1: W391 blank line at end of file

./openedx/core/djangoapps/appsembler/usage/apps.py:9:1: W391 blank line at end of file

./openedx/core/djangoapps/appsembler/usage/management/commands/aggregate_usage.py:132:9: E124 closing bracket does not match visual indentation

./common/djangoapps/student/views.py:133:5: W291 trailing whitespace

./common/djangoapps/student/views.py:353:80: W291 trailing whitespace

./common/djangoapps/student/views.py:1840:51: E712 comparison to True should be 'if cond is True:' or 'if cond:'

./common/djangoapps/student/views.py:1867:1: W293 blank line contains whitespace

./common/djangoapps/student/views.py:1872:25: W291 trailing whitespace

./common/djangoapps/student/views.py:1880:1: W293 blank line contains whitespace

./common/djangoapps/third_party_auth/models.py:237:5: E125 continuation line with same indent as next logical line

./common/djangoapps/third_party_auth/models.py:237:21: E123 closing bracket does not match indentation of opening bracket's line

./common/djangoapps/third_party_auth/pipeline.py:372:1: E302 expected 2 blank lines, found 1

./common/djangoapps/third_party_auth/pipeline.py:401:1: E302 expected 2 blank lines, found 1

./common/djangoapps/appsembler/urls.py:1:10: W291 trailing whitespace

./common/djangoapps/appsembler/urls.py:11:25: E124 closing bracket does not match visual indentation

./common/djangoapps/appsembler/urls.py:27:33: E201 whitespace after '('

./common/djangoapps/appsembler/urls.py:30:1: W293 blank line contains whitespace

./common/djangoapps/appsembler/management/commands/send_stats_to_intercom.py:11:45: W292 no newline at end of file
```

**Comment by OmarIthawi** [comment]
Wohooow :tada:

**Comment by thraxil** [comment]
[(8) get jenkins tests running against all relevant branches of edx-platform](https://trello.com/c/5noNKJy5/2713-8-get-jenkins-tests-running-against-all-relevant-branches-of-edx-platform)

**Comment by thraxil** [comment]
The pep8 issues are all sorted except these:

```
[quality_all] Number of pep8 violations: 11
[quality_all] ./lms/djangoapps/student_account/fields.py:17:26: W291 trailing whitespace
[quality_all] ./lms/djangoapps/student_account/fields.py:58:64: W291 trailing whitespace
[quality_all] ./lms/djangoapps/student_account/fields.py:68:34: W291 trailing whitespace
[quality_all] ./lms/djangoapps/student_account/fields.py:73:72: W291 trailing whitespace
[quality_all] ./lms/djangoapps/student_account/fields.py:75:12: W291 trailing whitespace
[quality_all] ./lms/djangoapps/student_account/fields.py:82:58: W291 trailing whitespace
[quality_all] ./lms/djangoapps/student_account/fields.py:87:1: W391 blank line at end of file
[quality_all] ./lms/djangoapps/student_account/views.py:537:1: W293 blank line contains whitespace
[quality_all] ./lms/djangoapps/student_account/views.py:543:73: W291 trailing whitespace
[quality_all] ./lms/djangoapps/student_account/views.py:563:26: W291 trailing whitespace
[quality_all] ./lms/djangoapps/student_account/views.py:566:14: W291 trailing whitespace
```

These ones are stumping me because `lms/djangoapps/student_account/fields.py` does not exist in the repo (and `views.py` doesn't match up with what it's reporting). So something in the course of the quality check (most likely prereq installs) is generating or pulling those files in from elsewhere. I have so far been unable to figure out where they are coming from. Can't really fix the pep8 errors until I figure out where they are.

**Comment by OmarIthawi** [comment]
@thraxil perhaps Jenkins is checking out a the wrong branch? That happened to me in the past, so to make sure that I keep my sanity I had some thing similar to:

```groovy
sh 'git status'
sh 'git log --oneline | head'
```

**Comment by thraxil** [comment]
Well, it's picking up the changes that I make to the PR, so I'm pretty sure it's checking the right code out.

**Comment by thraxil** [comment]
also, it's fairly clear in the logs:

```
Checking out git https://github.com/appsembler/edx-platform.git into /var/jenkins_home/jobs/edx-platform/workspace@script to read Jenkinsfile
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/appsembler/edx-platform.git # timeout=10
Fetching upstream changes from https://github.com/appsembler/edx-platform.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/appsembler/edx-platform.git  +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/225/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/225/merge^{commit} # timeout=10
Checking out Revision 7526d22bb1f95558581d88f760bc84125055d9d8 (refs/remotes/origin/pr/225/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 7526d22bb1f95558581d88f760bc84125055d9d8
Commit message: "Merge f2623771b843e4e8adc4cf00c3bcad62a4aab050 into 1b52219bd8c39a9c7297cc7e0b1f965db4e2be7b"
 > git rev-list --no-walk ba04923f6426eaa23d81b5229ebf950a173a1018 # timeout=10
```

**Comment by OmarIthawi** [comment]
Looks like it _is_ checking the right code. Based on the log you've provided, I've checked the following:

 - Go to https://github.com/appsembler/edx-platform/commit/7526d22bb1f95558581d88f760bc84125055d9d8
 - Click on ["Browse Files"](https://github.com/appsembler/edx-platform/tree/7526d22bb1f95558581d88f760bc84125055d9d8)
 - Click on [Find file](https://github.com/appsembler/edx-platform/find/7526d22bb1f95558581d88f760bc84125055d9d8)
 - Both files exists: [student_account/fields.py](https://github.com/appsembler/edx-platform/blob/7526d22bb1f95558581d88f760bc84125055d9d8/lms/djangoapps/student_account/fields.py) and [student_account/views.py](https://github.com/appsembler/edx-platform/blob/7526d22bb1f95558581d88f760bc84125055d9d8/lms/djangoapps/student_account/views.py)

 - Looking at the line [556 in views.py](https://github.com/appsembler/edx-platform/blob/7526d22bb1f95558581d88f760bc84125055d9d8/lms/djangoapps/student_account/views.py#L566), it indeed has trailing spaces.


Doing the same (mostly the same) check locally:

```
$ git co appsembler/feature/ficus-jenkinsfile
$ git ls-files | grep -e student_account/views.py -e student_account/fields.py
lms/djangoapps/student_account/fields.py
lms/djangoapps/student_account/views.py
```

The spaces also exists on my local machine:

<kbd></kbd>

**Comment by thraxil** [comment]
Aha! Yes. It's running the tests against the PR merged into the target branch. This commit: https://github.com/appsembler/edx-platform/commit/1b52219bd8c39a9c7297cc7e0b1f965db4e2be7b#diff-0d294bf2f469aac69d788a46b6aba1c3 introduced `fields.py` and was merged after the commit where I started my PR.

I rebased and I see it locally now as well.

**Comment by thraxil** [comment]
Tried skipping the whole test class for i18n tests since it's throwing an error during `setUpClass`. unittest docs say "Skipped tests will not have setUp() or tearDown() run around them. Skipped classes will not have setUpClass() or tearDownClass() run."

but it still errors :(

This one's frustrating because I also can't duplicate it locally. In my non-jenkins environment, that test runs fine.

**Comment by OmarIthawi** [comment]
I see ... a green ... check ... mark. Thank you @thraxil!

**Comment by OmarIthawi** [comment]
If you'd like a review, please consider squashing related commits. Otherwise the Jenkinsfile looks good.

**Comment by thraxil** [comment]
Yep. Squashing is planned. I was thinking about trying to get some of the other tests running again as well, but that's probably better left for another PR.

**Comment by OmarIthawi** [comment]
Probably it is. Thank you @thraxil!

**Pull request merged**
