### PR TITLE
Jenkinsfile for ginkgo

### PR DESCRIPTION
**Pull request by thraxil**
Jenkins tests for ginkgo. Pretty similar to ficus.

### CODE REVIEW

**Comment by thraxil** [comment]
pip install is failing on `recommender-xblock`

```
[test_lib_all]     Traceback (most recent call last):
[test_lib_all]       File "<string>", line 1, in <module>
[test_lib_all]       File "/tmp/pip-build-VVsYw3/recommender-xblock/setup.py", line 58, in <module>
[test_lib_all]         'install': XBlockInstall,
[test_lib_all]       File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
[test_lib_all]         dist.run_commands()
[test_lib_all]       File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
[test_lib_all]         self.run_command(cmd)
[test_lib_all]       File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
[test_lib_all]         cmd_obj.run()
[test_lib_all]       File "/tmp/pip-build-VVsYw3/recommender-xblock/setup.py", line 14, in run
[test_lib_all]         self.compile_translations()
[test_lib_all]       File "/tmp/pip-build-VVsYw3/recommender-xblock/setup.py", line 30, in compile_translations
[test_lib_all]         self.announce('Translations compilation failed: %s', ex.message)
[test_lib_all]       File "/usr/lib/python2.7/distutils/cmd.py", line 184, in announce
[test_lib_all]         log.log(level, msg)
[test_lib_all]       File "/usr/lib/python2.7/distutils/log.py", line 34, in log
[test_lib_all]         self._log(level, msg, args)
[test_lib_all]       File "/usr/lib/python2.7/distutils/log.py", line 21, in _log
[test_lib_all]         raise ValueError('%s wrong log level' % str(level))
[test_lib_all]     ValueError:  wrong log level
[test_lib_all]     
[test_lib_all]     ----------------------------------------
[test_lib_all]   Rolling back uninstall of recommender-xblock
[test_lib_all] Command "/tmp/ve/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VVsYw3/recommender-xblock/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8V3q8t-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/ve/include/site/python2.7/recommender-xblock" failed with error code 1 in /tmp/pip-build-VVsYw3/recommender-xblock/
```

**Comment by thraxil** [comment]
I don't get that error when I build a fresh virtualenv, so I think it's an odd interaction as a result of trying to pip install the ginkgo libraries on top of the "pre-warmed" ficus virtualenv in the docker container. Going to try just building a ginkgo-based container and using that.

**Comment by thraxil** [comment]
Spoke too soon... I get the same error when installing in a container. So now I'm thinking it's a debian vs ubuntu thing.

**Comment by thraxil** [comment]
[(8) get jenkins tests running against all relevant branches of edx-platform](https://trello.com/c/5noNKJy5/2713-8-get-jenkins-tests-running-against-all-relevant-branches-of-edx-platform)

**Comment by thraxil** [comment]
Built a new base image (off ubuntu; giving up on debian). Everything installs now. Pep8 passing.

Still some failing tests though and they are taking much longer to run than on ficus.

**Comment by thraxil** [comment]
One of the failures is the same sass/coffeescript related one that I ended up just skipping in ficus:

```[test_lib_all] FAIL: test_watch_theme_assets (pavelib.paver_tests.test_assets.TestPaverWatchAssetTasks)
[test_lib_all] ----------------------------------------------------------------------
[test_lib_all] Traceback (most recent call last):
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/pavelib/paver_tests/test_assets.py", line 213, in test_watch_theme_assets
[test_lib_all]     self.assertItemsEqual(sass_watcher_args[1], self.expected_sass_directories)
[test_lib_all] AssertionError: Element counts were not equal:
[test_lib_all] First has 1, Second has 0:  Path(u'/home/jenkins/workspace/edx-platform/common/test/test-theme/customer_specific/cms/static/sass')
[test_lib_all] First has 1, Second has 0:  Path(u'/home/jenkins/workspace/edx-platform/common/test/test-theme/customer_specific/lms/static/sass')
[test_lib_all] -------------------- >> begin captured stdout << ---------------------
[test_lib_all] ---> pavelib.assets.watch_assets
[test_lib_all] DINAMO: /home/jenkins/workspace/edx-platform/common/test/test-theme/customer_specific/lms/static/sass
[test_lib_all] DINAMO: /home/jenkins/workspace/edx-platform/common/test/test-theme/customer_specific/cms/static/sass
[test_lib_all] find /home/jenkins/workspace/edx-platform/lms /home/jenkins/workspace/edx-platform/cms /home/jenkins/workspace/edx-platform/common -type f -name "*.coffee"
[test_lib_all] Starting asset watcher...```

**Comment by thraxil** [comment]
Then there are a bunch of these unicode related failures:

```[test_lib_all] xmodule.modulestore.xml: ERROR: ERROR: Failed to load courselike 'test_unicode': 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128)
[test_lib_all] Traceback (most recent call last):
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 402, in try_load_course
[test_lib_all]     course_descriptor = self.load_course(course_dir, course_ids, errorlog.tracker, target_course_id)
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 581, in load_course
[test_lib_all]     self.content_importers(system, course_descriptor, course_dir, url_name)
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 609, in content_importers
[test_lib_all]     course_dir, url_name
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 637, in load_extra_content
[test_lib_all]     self._load_extra_content(system, course_descriptor, category, base_dir, course_dir)
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 671, in _load_extra_content
[test_lib_all]     for filepath in glob.glob(content_path / '*'):
[test_lib_all]   File "/usr/lib/python2.7/glob.py", line 27, in glob
[test_lib_all]     return list(iglob(pathname))
[test_lib_all]   File "/usr/lib/python2.7/glob.py", line 65, in iglob
[test_lib_all]     yield os.path.join(dirname, name)
[test_lib_all]   File "/tmp/ve/lib/python2.7/posixpath.py", line 73, in join
[test_lib_all]     path += '/' + b
[test_lib_all] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128)
[test_lib_all] --------------------- >> end captured logging << ---------------------
[test_lib_all] 
[test_lib_all] ===Flaky Test Report===
[test_lib_all] 
[test_lib_all] 
[test_lib_all] ===End Flaky Test Report===
[test_lib_all] ----------------------------------------------------------------------
[test_lib_all] Ran 1439 tests in 812.087s
[test_lib_all] 
[test_lib_all] FAILED (SKIP=77, errors=2, failures=1)```

**Comment by thraxil** [comment]
Then there are a bunch of tests that error out because they can't load `edxmako.shortcuts` for some reason:

```[test_lib_all] PluginError: No such plugin progress for entry point openedx.course_tab
[test_lib_all] xblock.plugin: WARNING: Unable to load XBlockAside 'tagging_aside'
[test_lib_all] Traceback (most recent call last):
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/xblock/plugin.py", line 146, in load_classes
[test_lib_all]     yield (class_.name, cls._load_class_entry_point(class_))
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/xblock/plugin.py", line 75, in _load_class_entry_point
[test_lib_all]     class_ = entry_point.load()
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2296, in load
[test_lib_all]     return self.resolve()
[test_lib_all]   File "/tmp/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in resolve
[test_lib_all]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/cms/lib/xblock/tagging/__init__.py", line 6, in <module>
[test_lib_all]     from .tagging import StructuredTagsAside
[test_lib_all]   File "/home/jenkins/workspace/edx-platform/cms/lib/xblock/tagging/tagging.py", line 12, in <module>
[test_lib_all]     from edxmako.shortcuts import render_to_string
[test_lib_all] ImportError: No module named edxmako.shortcuts```

`edxmako.shortcuts` is there in the code, so there must be something stopping it from being found or importing correctly.

**Comment by OmarIthawi** [comment]
Thanks again @thraxil!

**Comment by thraxil** [comment]
@OmarIthawi, no. I gave up on getting the debian-based `jenkinsci/jnlp-slave` based image working with ginkgo (see my first comment on `pip install` failing on `recommender-xblock` with errors about log levels) and went the opposite direction starting with an Ubuntu 16.04 base and getting the JVM/Jenkins stuff running on that.

Ficus is still using the old one. I could probably switch it over to this newer one and it would be fine, but I don't see any strong need to do that (it's working as-is).

**Comment by natea** [comment]
@thraxil i wouldn't worry too much about getting the Recommender XBlock working. I don't know anyone who's using it.

**Comment by thraxil** [comment]
@natea the issue is that since it's included in the requirements, the entire install halts on it. I assume it would be a relatively large change to remove it from the entire codebase.

**Comment by OmarIthawi** [comment]
@thraxil Please consider sharing how to maintain the docker image with the rest of the team (or just few of them). So we can enable the rest of the tests.

**Comment by thraxil** [comment]
@OmarIthawi it's in this PR: https://github.com/appsembler/dockerfiles-private/pull/2

**Comment by natea** [comment]
@thraxil yeah, I think we could just remove that one line from the requirements txt file and that would skip installing it.

**Comment by bryanlandia** [comment]
@thraxil Since it's been approved, go ahead and merge this one if you are satisfied.  Also, please check why the Appsembler team doesn't have access to dockerfiles-private repo.

**Pull request merged**
