### PR TITLE
nyif course access workflows

### PR DESCRIPTION
**Pull request by tkeemon**
There are two updates here:

First, I'm changing the method used to determine the Organization during a user registration. AMC relies on modifying the Site object to include a foreign key relationship with an Organization. Instead of taking that change, we're going to grab the `course_org_filter` from the SiteConfiguration. 

Second, the course about page has been updated to include the course access request workflow. This ties in with the microsite theme changes here: 
https://github.com/appsembler/edx-theme-customers/commit/37667b18f3018d607fa857737cc68075e6c606c9

If a manager indicates that a course requires special permission to access, a student can visit the course's about page, click on the "Enroll in COURSE_NAME" button, then a request will be sent to the manager.

### CODE REVIEW

**Comment by tkeemon** [comment]
[(6) NYIF: test CCA workflows for Ficus upgrade](https://trello.com/c/wZdflEAn/2049-6-nyif-test-cca-workflows-for-ficus-upgrade)

**Comment by tkeemon** [comment]
@melvinsoft I know what you mean. We're trying to add some additional functionality into the view, so I don't think we have any other options. But I'm open to suggestions. 

I made sure to check for the necessary packages and gracefully handle exceptions if they don't exist. From the perspective of a customer without these customizations, nothing will have changed.

**Comment by melvinsoft** [comment]
@tkeemon Yes, I agree, sometimes there is no other option than change platform code. I'm going to approve the PR, please make sure that we document the change in the project docs maybe, so we don't missing it while merging to Ginkgo.

**Comment by tkeemon** [comment]
Will do. Thanks @melvinsoft

**Pull request merged**
