### PR TITLE
remove mongo_conn setting

### PR DESCRIPTION
**Pull request by estherjsuh**
Remove setting from `mongo_conn` as Atlas certificate is not invalid.

### CODE REVIEW

**Comment by estherjsuh** [comment]
@OmarIthawi I should run this command after the PR is merged?

`$ git checkout origin/open-release/juniper.master -- common/lib/xmodule/xmodule/mongo_utils.py
`

**Review by thraxil — APPROVED** [review]

**Comment by OmarIthawi** [comment]
> @OmarIthawi I should run this command after the PR is merged?
> 
> `$ git checkout origin/open-release/juniper.master -- common/lib/xmodule/xmodule/mongo_utils.py `

Please run it before this PR is merge.

An alternative (and perfectly fine) way is to do the following:

 - Go to upstream: https://github.com/edx/edx-platform/blob/open-release/juniper.master/common/lib/xmodule/xmodule/mongo_utils.py
 - Copy the entire file
 - Paste it locally into `esther/remove-mongo-setting`
 - Commit and push

**Review by OmarIthawi — APPROVED** [review]

**Comment by estherjsuh** [comment]
@OmarIthawi I pushed the code to upstream - could you please take a final look before I merge?
Thank you!

**Review by OmarIthawi — APPROVED** [review]

**Comment by OmarIthawi** [comment]
> @OmarIthawi I pushed the code to upstream - could you please take a final look before I merge?
> Thank you!

Looks just great! Thank you for walking the extra mile on this!

**Pull request merged**
