### PR TITLE
add the ability to clean up usernames for SSO autoregister

### PR DESCRIPTION
**Pull request by melvinsoft**
We detected throw the SSO work, that many IdP from our customers release the username attribute in an email format. And edX doesn't allow special chars in the usernames. This small commit adds the ability for clear email into usernames. 

The new lines do the following:
- remove the domain part from the email, if exists.
- remove any special character from the local part.
- adds a random int (length=3) for avoid duplicates.

The new functionality relies on FEATURE flag `TPA_CLEAN_USERNAMES`

### CODE REVIEW

**Comment by tkeemon** [comment]
@melvinsoft I'm not very familiar with this part of the codebase. Does `suggested_username` simply autofill the username field on the registration page? If so, then this looks good to me. I know we want it in our codebase, but is this something we can contribute back to edX?

**Comment by melvinsoft** [comment]
@tkeemon thanks for review this! I added one commit. I added the functionality for controlling the cleanup process a little bit. Take a look and let me know.
I agree, adding this changes this could be a contribution, maybe @bezidejni and @bryanlandia can take a look to.

**Comment by melvinsoft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2m9wnSZR&#x2F;505-3-hioa-sso-with-their-saml-based-system-feide"> (3) HIOA: SSO with their SAML-based system (FEIDE)</a>

**Comment by tkeemon** [comment]
@melvinsoft just to clarify: I'm curious as to whether or not `suggested_username`:
1. just populates the username fields of /register
2. or whether TPA tries to create an Open edX user with that username. 

My concern (if it's 2) is that usernames must be unique and 2 isn't checking that criteria, so the suggested username might already exist in the DB.

**Comment by melvinsoft** [comment]
@tkeemon This only populates the register form, and set a variable for auto-submit the form. If a user with that username or email already exists, the register form is displayed to the user informing the problem. The user can fix the attribute and submit the form again.

**Comment by bryanlandia** [comment]
@melvinsoft This looks good to me though I'm not really familiar with TPAuth.  For a contribution to Open edX, should probably have some test coverage, but seems like something good to contribute, and simple/self-contained. Nice!

**Comment by melvinsoft** [comment]
@briandant @tkeemon are good to merge this?

**Pull request closed without merging**
