### PR TITLE
fix course deletion from elasticsearch

### PR DESCRIPTION
**Pull request by melvinsoft**
The sysadmin dashboard is performing CMS workflows from the LMS. When a course is deleted, the signal for delete the course from elastic is being triggered, but is failing silently, because the CourseAboutSearchIndexer class, that is the responsible for index and delete course form elastic search, it's failing silently. the problem is that this class is in file inside the cms app, and it has some imports with relative paths.

This PR introduces some of code in the sysadmin dashboard code, for:
- Manually delete the course overview.
- Delete the course from elastic search.
- Add information to the message.

### CODE REVIEW

**Comment by melvinsoft** [comment]
@tkeemon @bryanlandia 

I've deployed the branch on a test server. 

http://104.197.248.109/
http://104.197.248.109:18010
You can use the edX default users.

Test steps:
1 - Create a course.
2 - Check that is present in course overview and and search (find courses)
3 - Go to sysadmin dashboard and delete the course
4 - Check course overview, the course must be gone (check browser cache)
5 - Go to find courses and check that the course is not anymore.

**Comment by melvinsoft** [comment]
[Fix course deletion on sysadmin dashboard, for delete course search and overview properly.](https://trello.com/c/FMimfSyh/730-fix-course-deletion-on-sysadmin-dashboard-for-delete-course-search-and-overview-properly)

**Comment by natea** [comment]
@melvinsoft is this a fix we should push upstream, so that it gets fixed in edx-platform once and for all!?

**Comment by melvinsoft** [comment]
@natea I'm not 100% percent comfortable with this solution, because is not solving the real problem, the correct signal is being triggered by modulestore, but is still failing silently. This fix is still stable, but is not elegant. I think think this works for now, for some urgent customer requests, and also give us some air for think a better fix.

**Comment by bryanlandia** [comment]
Hi @melvinsoft - What is the latest on this PR?  Did this ever get fixed?

**Comment by melvinsoft** [comment]
@bryanlandia This solves the problem but not the bug, this removes the course overview and elastic search entry when you deleted a course from sysadmin dashboard, but the errors are still occurring, because the sysadmin dashboard executes `cms` from the `lms` and that causes a failure on the signals.

Since the sysadmin dashboard has been deprecated on Eucalyptus, we discarded this PR.

**Comment by bryanlandia** [comment]
@melvinsoft OK, is this worth doing anything with then?  If so, we could rebase off of a NYIF and/or/ InterSystems branches so our biggest Dogwood customers get the fix.

**Comment by melvinsoft** [comment]
@bryanlandia Ok, I've tracked down the card, at the end the code change wasn't necessary, it can be fixed from the complete button itself. I'm going to close this PR without merge it.

**Pull request closed without merging**
