### PR TITLE
Cypress fix mathjax CDN

### PR DESCRIPTION
**Pull request by melvinsoft**

### CODE REVIEW

**Comment by melvinsoft** [comment]
[(6) cdn.mathjax.org End of Life](https://trello.com/c/tGM7dLO4/1519-6-cdn-mathjax-org-end-of-life)

**Comment by johnbaldwin** [comment]
@melvinsoft missing this fix: https://github.com/appsembler/edx-platform/blob/appsembler/feature/mergeCypress/common/templates/mathjax_include.html#L53

**Comment by johnbaldwin** [comment]
Other than updating the HTML file, GTG!

**Comment by melvinsoft** [comment]
@johnbaldwin Thanks! change addressed!

**Pull request merged**
