### PR TITLE
Fix Internet Explorer JS error on course outline

### PR DESCRIPTION
**Pull request by grozdanowski**
Students are unable to expand any topics in the Course page using IE 11.

**Reason**
Internet Explorer is something that no one should be using, since it is a lame excuse for a web browser. Essentially it doesn't follow modern JS standards. This is usually resolved using babel polyfills, however Hawthorn has an issue where it uses out dated polyfills that don't address the issue with IE where it doesn't seem to understand that `Array` can have a `from` method. Well, it is how it is. Stupid and bad.

**Solution**
With help of George Babey from edX I have added the polyfill that helps in this issue manually. Tested it out with IE and it works.

_There was much rejoicing. People were cheering. Proud mothers crying._

### CODE REVIEW

**Comment by johnbaldwin** [comment]
@grozdanowski Do we want to merge this into `appsembler/tahoe/develop` first, THEN merge do `appsembler/tahoe/master`, or is this a straight to `master` and merge or rebase `master` to `develop` type PR? cc @melvinsoft

**Comment by grozdanowski** [comment]
Agh sorry, I just wanted to get this to production - this heat wave melts my brain. We can go and merge whenever you guys feel would be wiser. It's not that this is a super duper urgent "by tomorrow" fix.

**Comment by johnbaldwin** [comment]
So let's merge this into development. I'll change the target for the PR. Then when merged, we'll cut a new RC tag to push to staging

**Comment by johnbaldwin** [comment]
@melvinsoft What say you? Should we change the merge target to `appsembler/tahoe/develop`?

**Pull request merged**
