### PR TITLE
instrument CoursewareIndex and related functions

### PR DESCRIPTION
**Pull request by thraxil**
Beginning the process of instrumenting to figure out the problem behind https://appsembler.atlassian.net/browse/RED-1066

The view in question is `CoursewareIndex`, so we start by instrumenting all the functions/methods that it calls directly. This
should help us narrow it down.

### CODE REVIEW

**Comment by melvinsoft** [comment]
I agree with @OmarIthawi comment here, I'm worried about the diffs, but this is an ugly one, and it deservers the attention and changes.

**Comment by thraxil** [comment]
Yeah, I've been trying to stick to very minimal instrumentation in the upstream code. You should be able to find every line of it by grepping for `beeline`, so it will be easy to remove when we want to.

**Comment by karka86** [comment]
Having said about the merge with Juniper/Ironwood. When is it likely to happen. Any idea?

**Comment by OmarIthawi** [comment]
> Having said about the merge with Juniper/Ironwood. When is it likely to happen. Any idea?

@karka86 Hello there!

**Comment by karka86** [comment]
Hello @OmarIthawi !

**Comment by OmarIthawi** [comment]
> Having said about the merge with Juniper/Ironwood. When is it likely to happen. Any idea?

@karka86 it's on our radar but we don't know when. May I know why you're asking this?

**Pull request merged**
