### PR TITLE
NXP taxoman integration - Facet display order/sorting

### PR DESCRIPTION
**Pull request by johnbaldwin**
1. Added a facet 'display_order' field and a term/facet_value 'display_order' field to the backbone.js UI code

2. Set the edx-search repo branch to `appsembler/taxoman_integration` so that the Taxoman updates will be used

### CODE REVIEW

**Comment by johnbaldwin** [comment]
[(16) NXP Taxoman Arbitrary Sort](https://trello.com/c/u0XgQWrr/1511-16-nxp-taxoman-arbitrary-sort)

**Comment by johnbaldwin** [comment]
@bryanlandia Manually tested different configurations of existance/non-existance of display_order and values (None/null, string so that we've tested with non-numeric values) and course discover does not blow up. So tested: Facet has display order, facet_value does not, facet does not have display order, facet_value does. Fortunately the backbone compare for sorting is generic, so we don't have to worry about the type of the value we're comparing. I did not test if the display_order was a collection. 

Just to note: I really want to get some automated testing for states of the server and of the backbone client.

**Comment by bryanlandia** [comment]
@johnbaldwin - Sorry didn't see your reply to my question here for quite a while!   I'll go ahead and approve then since you've addressed my one concern.

**Comment by bryanlandia** [comment]
@johnbaldwin For some reason I am not seeing Review or Approve buttons but I do approve it if you want to merge.

**Comment by johnbaldwin** [comment]
@bryanlandia Thanks!

**Comment by johnbaldwin** [comment]
Closed PR. Will not merge as no longer needed for NXP. Added feature to new branch `appsembler/ficus/feature/taxoman_integration`

**Pull request closed without merging**
