### PR TITLE
Tahoe: Get Ficus updates into Hawthorn

### PR DESCRIPTION
**Pull request by OmarIthawi**
### The Plan!

 - [x] Needs https://github.com/appsembler/edx-platform/pull/344 to get merged first.
 - [x] Update with `appsembler/amc/master`
 - [x] Fix conflicts
 - [x] Address the TODOs below
 - [x] Review and Merge 

---

- [x] **1. In Django Startup**
```
from track.shim import DefaultMultipleSegmentClient

    ...
    if settings.LMS_SEGMENT_KEY:
        analytics.write_key = settings.LMS_SEGMENT_KEY
        if settings.LMS_SEGMENT_SITE:
            analytics.default_client = DefaultMultipleSegmentClient()
```

- [x] **In lms/test.py**

```
#
# Settings for Tahoe API
#
INSTALLED_APPS += ('openedx.core.djangoapps.appsembler.api',)
```

- [x] **In lms/aws.py**
John's: Disable devstack cache

- [x] **In cms/amc.py** 
`EmailBackend`

```
        if MANDRILL_API_KEY:
            EMAIL_BACKEND = ENV_TOKENS.get('EMAIL_BACKEND', 'anymail.backends.mandrill.EmailBackend')
            ANYMAIL = {
                "MANDRILL_API_KEY": MANDRILL_API_KEY,
            }
            INSTALLED_APPS += ("anymail",)
```

- [x] **Same goes for lms/amc.py** 
Same as :point_up: 

- [x] **Lms envs/dev.py**
Added `LMS_SEGMENT_SITE = os.environ.get('SEGMENT_SITE')`

- [x] **Figures changes in LMS/envs/devstack**
```
        # Webpack loader needed by Figures
        if 'webpack_loader' not in INSTALLED_APPS:
            INSTALLED_APPS += ('webpack_loader',)

        # Enable Figures if it is included
        if 'figures' in INSTALLED_APPS:
            import figures
            figures.update_settings(
                WEBPACK_LOADER,
                CELERYBEAT_SCHEDULE,
                ENV_TOKENS.get('FIGURES', {}))
```

- [x] **Bryan's in student/views.py**

```
        def _cert_info(user, course_overview, cert_status, course_mode):  # pylint: disable=unused-argument
            ...

            # open-ended courses should not display the 'processing' message
            default_status = 'unavailable' if not course_overview.end else 'processing' 
```

- [x] **student/views.py**
Added `send_activation_email_flag` to:

`def create_account_with_params(request, params, send_activation_email_flag=True):`

and also `send_activation_email_flag` inside `create_account_with_params`:

```
            if send_email and send_activation_email_flag:
                dest_addr = user.email
                context = {
                    'name': profile.name,
                    'key': registration.activation_key,
                }
```

- [x] **User API views.py**

```
        terms_link = marketing_link("TOS")

        if configuration_helpers.get_value('combine_privacy_and_tos', False):
            terms_label = _(u"Terms of Service and Privacy Policy")
            terms_text = _(u"Review the Terms of Service and Privacy Policy")
        else:
            terms_label = _(u"Terms of Service")
            terms_text = _(u"Review the Terms of Service")
```

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(2) Hawthorn: Sync with Ficus branches](https://trello.com/c/PJHIhP3E/3668-2-hawthorn-sync-with-ficus-branches)

**Comment by OmarIthawi** [comment]
@thraxil and @melvinsoft Could you please review this?

I've fixed all the known TODOs, so please take a look at commits starting from and after `Hawthorn support for LMS_SEGMENT_SITE variable`, as those are related to recent work that we've been doing on Ficus.

**Comment by abeals** [comment]
@OmarIthawi Thanks for doing this difficult and detail-oriented work.

This changelog looks like another todo list of sorts: which of these changes we've made in our branch can be (a) pushed upstream, or if that's not possible, (b) pulled out of edx-platform into a plugin?

@melvinsoft Thinking particularly about the Segment changes, but there are others here.

**Comment by OmarIthawi** [comment]
Thanks @abeals for checking here. 

This is just a sync for the work that we did on Ficus after we started on Hawthorn, so unfortunately we have a ton more in the code that doesn't appear in the pull request, but instead via a diff `$ git diff open-release/hawthorn.2`.

I don't have any answers for your questions now. But depending on our priorities, I think we probably want to make that our next priority after Hawthorn. Which is to decustomize, upstream and externalize our Tahoe modifications.

cc: @melvinsoft

**Pull request merged**
