### PR TITLE
Add shell commands and admin panel to set AMC admins

### PR DESCRIPTION
**Pull request by OmarIthawi**
This is an admin view (and a django shell command) for superusers to allow CSMs to make a user an AMC admin for an organization and its site, while showing those access and refresh tokens for CSMs to copy to AMC.

This is a hacky feature that has a lot of assumptions with not much bailout (except by failing with 500 error):

 - An organization should have one, and only one site.
 - There's only one access token for the AMC OAuth2 Client.
 - Only one refresh token for that.
 - Superusers will not just set users to be admins, except for those who are legit users.

The architecture of this view is largely guided by this tutorial:

 - [How to Add Custom Action Buttons to Django Admin
](https://medium.com/@hakibenita/how-to-add-custom-action-buttons-to-django-admin-8d266f5b0d41)

### TODO

 - [x] Basic implementation
 - [ ] Tests
 - [ ] Manual testing

### Reviewers

Please do check it out, and let me know what do you think. I need:

 - [x] One light review (@thraxil, perhaps) 
 - [x] Another more extensive one, from @melvinsoft.

Please indicate which one you have done, as we will probably add more of those custom pages in the future for CSMs.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(8) Enable CSMs to solve the missing Access and Refresh keys issues + organization assignment](https://trello.com/c/I3d73aeE/3511-8-enable-csms-to-solve-the-missing-access-and-refresh-keys-issues-organization-assignment)

**Comment by OmarIthawi** [comment]
@thraxil You're right, tests are good. I was thinking of the plan below for writing tests:

 - **Admin:** No tests, except for one happy scenario for the admin view. Should help to find errors when moved to new releases.
 - **Shell command:** Not tests.
 - **Utils:** Focus mainly on happy and well known scenarios.

What do you think?

**Comment by melvinsoft** [comment]
@OmarIthawi I could get around to this yet. Top priority for Monday.

**Comment by OmarIthawi** [comment]
Thank you @melvinsoft!

**Comment by OmarIthawi** [comment]
Thanks @melvinsoft @thraxil! I'll merge this without tests. This is something we ideally want to deprecate soon. 

I think we can afford having it broken sometimes as it's only meant for as a stopgap solution for superusers.

We need to focus on actually solving the problem, and this is where our efforts should go.

**Comment by OmarIthawi** [comment]
Two blunders here! I forgot to squash the commits and also merged directly to `appsembler/amc/master` :unamused:

**Pull request merged**
