### PR TITLE
Hawthorn for Tahoe

### PR DESCRIPTION
**Pull request by OmarIthawi**
### Merge Issues
 - [x] **Anders:** A Jenkins has been introduced by edX, I've used edX's instead of ours. Feel free to open another pull request to reuse and edit. [Trello Card](https://trello.com/c/i8Gm7i11).
 - [x] **Omar:** Double check if `domain_override=request.get_host()` is correctly implemented in `lms/djangoapps/appsembler_api/utils.py`. [Trello Card](https://github.com/appsembler/edx-platform/pull/281).
 - [x] **Omar:** Check if `django_login(request, new_user)` is being used correctly with `SKIP_LOGIN_AFTER_REGISTRATION`
 - [x] **Maxi:** The theming dirs updates had a lot of merge issues, I've done what I could. But we need to ensure that it's working well. [Trello Card](https://trello.com/c/OdxEBAq9).
 - [x] **Maxi:** Should we use `LMS_ROOT_URL` instead of `get_lms_link_from_course_key`, when possible?
 - [x] **Maxi:** We need to revisit how the user-to-site linking is done, same note from Ginkgo.
 - [x] **Bryan:** The certificates had a lot of merge issues. I've done what I could. But we need to ensure that it's working well. [Trello Card](https://trello.com/c/neKiWzvj/3110-hawthorn-re-test-tahoes-certificate).

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(8) Merge the Tahoe Branch with the Hawthorn Release](https://trello.com/c/QWvo9EJU/3313-8-merge-the-tahoe-branch-with-the-hawthorn-release)

**Comment by OmarIthawi** [comment]
Thanks @thraxil!

Do you mind doing a sanity check to see if we've got all the correct commits? I hate to be wrong, but I hate it more if it was on production :smile: 

GitHub says it's 5000+ commits:

image

**Comment by melvinsoft** [comment]
@OmarIthawi 

> The theming dirs updates had a lot of merge issues, I've done what I could. But we need to ensure that it's working well.
Yes, this is a risk area, probably we'll need some insights from @grozdanowski I think is gonna be better to debug it after the merge.

> Should we use LMS_ROOT_URL instead of get_lms_link_from_course_key, when possible?
Good question: I don't think so, `LMS_ROOT_URL` isn't microsite aware. `get_lms_link_from_course_key` provides the site URL, for the particular microsite.

>  We need to revisit how the user-to-site linking is done, same note from Ginkgo.
Same as Hawthorne, I'd say to tackle this a separate task.

**Comment by OmarIthawi** [comment]
Thanks @melvinsoft! I've added a couple of follow up cards to Trello. I'm merging.

**Comment by bryanlandia** [comment]
Hi @OmarIthawi Wow, this looks like it was a lot of work.  I can retest certificates.  Is there a record of the merge issues/conflicts somewhere?

**Pull request merged**
