### PR TITLE
Fixed milestone issues on Ficus

### PR DESCRIPTION
**Pull request by OmarIthawi**
This is a cherry-pick from edX upstream (https://github.com/edx/edx-platform/pull/14758 and https://github.com/edx/edx-platform/pull/15623)  to solve an issue with course prerequisites (check Trello card).

**Note:** I'm a co-author of the original PR, despite what git thinks :smile:. So, I've already tested it on both Dogwood and Open edX `master` (at the time).

### TODO
 - [x] Ensure the tests works well locally
 - [x] Do a quick manual test
 - [x] Code review, then:
   - [ ] Make the Ginkgo branch pull request by @OmarIthawi
   - [ ] Make the AMC branch pull request @melvinsoft

### CODE REVIEW

**Comment by thraxil** [comment]
Can one of the admins verify this patch?

**Comment by OmarIthawi** [comment]
@thraxil are you a chat bot? 0-minute difference between the PR and your comment :scream:

**Comment by OmarIthawi** [comment]
[(8) Platform-Wide: Changing prerequisites does not get passed to the backend.](https://trello.com/c/QGnUN7p6/2503-8-platform-wide-changing-prerequisites-does-not-get-passed-to-the-backend)

**Comment by abeals** [comment]
@thraxil which admins do you mean? Github admins?

> Can one of the admins verify this patch?

**Comment by thraxil** [comment]
Yeah, sorry. I'm pretty sure that came from jenkins (I've been working on getting it set up to build PRs). I don't exactly know what that message refers to though.

**Comment by OmarIthawi** [comment]
@amirtds @tkeemon could you please take a look?

**Comment by OmarIthawi** [comment]
@melvinsoft time to get this merged in AMC so customers can live happily ever after.

**Pull request merged**
