### PR TITLE
fix: YouTube video transcrips Import

### PR DESCRIPTION
**Pull request by amirtds**
## Background
https://appsembler.atlassian.net/browse/BLACK-2163
By the end of 2021 YouTube Deprecated their Timedtext API. This caused problem for our customers to download automatically the transcripts for their YouTube video for their videos in Open edX. Open edX team is aware of this error https://openedx.atlassian.net/browse/TNL-9460, but there was no movement on solving this issue from open edx end.
We tried to solve this by replacing the API with a new YouTube API, but the new API requires OAuth authentication and only works with videos in the same channel and even with corresponding changes in the codebase the Transcripts didn't work. 
## Our solution
I developed a new API that responds with SRT version of transcripts for a given YouTube video ID for example https://us-central1-penn-state.cloudfunctions.net/youtube-transcript?video_id=AcZZlbWRyUM You can try this with different videos just replace what comes after `video_id=` with your YouTube video ID.
After receiving the Transcripts from our API we make a call to `transcripts/upload` to upload the transcript for a given unit component location, and we store the transcripts. To make it visible in Studio and LMS.
The functionality should work as the following video

https://user-images.githubusercontent.com/5863396/156259990-b4d76898-425d-4102-8cde-c2ebd81480c6.mp4

### CODE REVIEW

**Review by johnbaldwin — APPROVED** [review]
Wow, that's all that is needed to download and process SRT files?

**Comment by johnbaldwin** [comment]
Is this a fix that should also go into Tahoe?

**Comment by amirtds** [comment]
Thanks @johnbaldwin Yes Tahoe needs a similar fix, but we can't merge this PR to our Juniper branch I need to check changes we had from Ginkgo to Juniper and will open new PR.

**Review by OmarIthawi — APPROVED** [review]
Thanks a lot @amirtds! Let me know when you make the Juniper pull request.

I think this is something worth contributing upstream.

**Pull request merged**
