### PR TITLE
update copy on market dropdown label

### PR DESCRIPTION
**Pull request by mbifulco**
Fix GYMX-111

@tkeemon - this is a small change, and a tiny PR.  I don't think we'll have any upcoming changes to our edx-platform repo in the next week or so, but I wanted to get this one in for our QA team to look at.  I am putting together a larger one for our theme which will come your way in a few days.

### CODE REVIEW

**Comment by tkeemon** [comment]
I'm going to try merging this in, but we might need to redo it. 

I committed a fix last night that included a missing select tag: 
https://github.com/appsembler/edx-platform/commit/c64fa6d7429ef4fa72dde8883ba681080e0239cd

and the DATA_DIR fix from this morning: 
https://github.com/appsembler/edx-platform/commit/4e5f6da643ee43924adc6ccb1bd955b9648791d0

but both of those commits seem to be missing from the PR. I'm curious to see how this will work. My intuition is that this won't be a fast-forward merge, but I'm hoping that it will work with add your fix and retain the previous two commits.

**Comment by tkeemon** [comment]
Everything looks good on the server. I think a rebase would have made the git history a bit cleaner, but all of the functionality is where it's supposed to be and everything on the server is working as expected.

**Comment by mbifulco** [comment]
Thanks - should I run a rebase sometime soon? Do you know how long it'll be
until Birch.2?

On Thu, Aug 6, 2015 at 10:03 AM, TJ Keemon <notifications@github.com> wrote:

> Everything looks good on the server. I think a rebase would have made the
> git history a bit cleaner, but all of the functionality is where it's
> supposed to be and everything on the server is working as expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appsembler/edx-platform/pull/6#issuecomment-128376163>
> .
>



-- 

Mike Bifulco

Director of Technology




The Revolution in Digital Design Education: Aquent Gymnasium
<http://gymnasium.aquent.com/>
m: 203.231.3445

As always, if you no longer want to receive communications from Aquent,
just let us know!

**Comment by natea** [comment]
@mbifulco birch.2 was announced 22 hrs ago. https://groups.google.com/d/msg/openedx-ops/pjVRMgTOqvM/MP6U9hkrHQAJ

**Comment by tkeemon** [comment]
At this point you can just do a git pull and everything should be up to date.

My plan is to merge birch.2 early next week. So if you're planning on doing any work on edx-platform between now and then, we might want to try rebasing your next PR on top of birch.2.

It's not a huge deal either way though.

**Comment by mbifulco** [comment]
22 hours! I feel so out of touch ;)

**Pull request merged**
