### PR TITLE
Security Patch - BLACK-1545

### PR DESCRIPTION
**Pull request by shadinaif**
## Change description

For [Hawthorn Master](https://github.com/appsembler/edx-platform/tree/appsembler/hawthorn/master): Security Patch - BLACK-1545. 

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

https://appsembler.atlassian.net/browse/BLACK-1545
https://appsembler.atlassian.net/browse/RED-2867

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Review by bryanlandia — CHANGES_REQUESTED** [review]
Thanks @shadinaif ! 

Looks like this one addresses all of one patch but not another.  Please see Jira ticket for rest of response, as this is  a public repo.

**Review by bryanlandia — COMMENTED** [review]
Thanks @shadinaif ! Sorry this part was such a pain.  It look good, I'm just going to try running this branch in a Hawthorn devstack and run tests.... unless you have.

**Comment by bryanlandia** [comment]
@shadinaif I was wondering if you had already run tests on this in a Hawthornd devstack branch.  Let me know.

**Comment by shadinaif** [comment]
closing for no activity...

**Pull request closed without merging**
