### PR TITLE
Fixed milestone issues

### PR DESCRIPTION
**Pull request by melvinsoft**
In settings_handler and any_unfulfilled_milestones (for mobile APIs)

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@melvinsoft just a reminder about this PR.

**Comment by melvinsoft** [comment]
@OmarIthawi Sorry the delay on this was, I've run all the test locally and is working properly. Also I´ve squashed the commits.

Please give it a final look and let me know if is ready to merge.

Thanks!

**Comment by OmarIthawi** [comment]
Looks good! Thanks @melvinsoft! I'm sure Cybereason folks would be happy :wink:

**Comment by melvinsoft** [comment]
@OmarIthawi Thanks!

**Pull request merged**
