### PR TITLE
Revert "Prep to update the Tahoe languages"

### PR DESCRIPTION
**Pull request by melvinsoft**
Reverts appsembler/edx-platform#380

@OmarIthawi The previous PR broke Studio due to a version conflict, I'm reverting it until you get back and we can see it with more detail.

### CODE REVIEW

**Comment by melvinsoft** [comment]
Agreed, thanks @thraxil

**Comment by OmarIthawi** [comment]
:unamused: If you keep `edx-i18n-tools`, it's broken. If you fix it, it's also broken. I have to find a better creative way! Thanks @melvinsoft for fixing the Studio.

**Comment by melvinsoft** [comment]
@OmarIthawi Agh, sorry to hear that. Is this a requirements in order to upgrade our translations?

**Comment by OmarIthawi** [comment]
Yes @melvinsoft, otherwise it's almost impossible to update the translations. I've addressed it in a better way on #393

**Pull request merged**
