### PR TITLE
backporting https://github.com/edx/edx-platform/pull/27359

### PR DESCRIPTION
**Pull request by amirtds**

### CODE REVIEW

**Comment by bryanlandia** [comment]
@amirtds Is this a draft PR still or would you like a review?

**Comment by amirtds** [comment]
Thanks @bryanlandia for checking, this is still WIP forgot to label it.

**Review by bryanlandia — CHANGES_REQUESTED** [review]
It looks like the change to the function signature (adding `user_id`) of `VisibleBlocks` here will break `VisibleBlocks.bulk_get_or_create` at https://github.com/appsembler/edx-platform/pull/931/files#diff-140e988679cdc0fe6c24f365fb6e0d42036db5ca6af2008e4c64f66f5ddcfaf0R281 .  I would take a look upstream in earlier commits and see where else calls to `VisibleBlocks.bulk_get_or_create` might break.  `bulk_get_or_create` will also need `user_id` as a param to be able to pass to `bulk_create`.

**Review by bryanlandia — APPROVED** [review]
Looks good now!

**Pull request merged**
