### PR TITLE
Dogwood: MathJax CDN update

### PR DESCRIPTION
**Pull request by johnbaldwin**
Dogwood: Mathjax: Update CDN from cdn.mathjax.org because that CDN service is going away

### CODE REVIEW

**Comment by johnbaldwin** [comment]
[(6) cdn.mathjax.org End of Life](https://trello.com/c/tGM7dLO4/1519-6-cdn-mathjax-org-end-of-life)

**Comment by johnbaldwin** [comment]
@tkeemon Thanks, updating now

**Comment by johnbaldwin** [comment]
@tkeemon I can't seem to find #3 and #4 in dogwood. I think these are generated files. on which system did you see them?

**Comment by tkeemon** [comment]
3. https://github.com/appsembler/edx-platform/blob/appsembler/feature/mergeDogwood.3/cms/static/coffee/spec/main_squire.coffee#L45
4. https://github.com/appsembler/edx-platform/blob/appsembler/feature/mergeDogwood.3/cms/static/coffee/spec/main.coffee#L54

**Comment by johnbaldwin** [comment]
Looks like those files (.js in the coffee directory) were generated. I did a full grep on all the files in edx-platform for `cdn.mathjax.org` and none turned up, so I think we are GTG.

**Comment by johnbaldwin** [comment]
@tkeemon I updated the coffee files. Please review

**Pull request merged**
