### PR TITLE
Fix Multi-tenant bug with rescore_problem tasks

### PR DESCRIPTION
**Pull request by shadinaif**
## Change description

Fix Multi-tenant bug with `rescore_problem` tasks

Instructors cannot rescore problems because our Multi-tenant `APPSEMBLER_MULTI_TENANT_EMAILS` option forces the use of `get_user_by_username_or_email` which requires a valid `request`. This fix is to add an option for passing the organization to `get_user_by_username_or_email_inside_organization` instead of fetching it from the current request. The optional argument will be used by `_get_modules_to_update`

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

Related issue: https://appsembler.atlassian.net/browse/RED-3247

### Development

- [x] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Comment by shadinaif** [comment]
Tested on staging @OmarIthawi , and it's working and looks fine

**Review by OmarIthawi — CHANGES_REQUESTED** [review]
needs further review and needs test cases.

please don't merge yet.

**Comment by shadinaif** [comment]
Thank you @OmarIthawi. I've added tests to better explain the change. `test_get_modules_to_update` with `option_value=True` will fail without the fix

**Review by thraxil — APPROVED** [review]

**Review by OmarIthawi — APPROVED** [review]
Looks great!

**Pull request merged**
