### PR TITLE
Gymnasium theme setup

### PR DESCRIPTION
**Pull request by tkeemon**

### CODE REVIEW

**Comment by mbifulco** [comment]
Comment comment

**Comment by tkeemon** [comment]
@mbifulco, the way we configure an Open edX instance is via /edx/app/edx_ansible/server-vars.yml  

We can create the server-vars.yml file: 
```
---
EDXAPP_PLATFORM_NAME: 'Gymnasium'
edxapp_use_custom_theme: true
edxapp_theme_name: "gymnasium"
edxapp_theme_source_repo: 'https://github.com/appsembler/edx-theme.git'
edxapp_theme_version: 'appsembler/gymnasium'
```

And the next time we run `/edx/bin/update edx-platform gymnasium/release` those changes will be made to the server. A lot of the questions we asked during the onboarding call a couple weeks ago are changes that are going to go into this server-vars.yml file.

The advantage of doing things this way is that the gymnasium/release branch will stay exactly the same as our appsembler/release branch. That makes pulling in new features developed off of the appsembler/release branch much faster and safer.

When we do come to the point where we need to hack on edx-platform to integrate a new feature, that's when we'll start making changes to the gymnasium/release branch. 

I'll leave this pull request open in case you've made some changes that haven't been pushed to github yet.

**Comment by mbifulco** [comment]
@tkeemon Got it - I had made essentially those changes on the vagrant machine I've got EdX stood up on locally (and not in the server-vars.yml file).  It's good to know there's a correct place for those changes in source control, thanks!  

Should the theme still be pointed to appsembler's theme?  We could set up a gymnasium/release branch in our repo to use, so that it doesn't need to be replicated in your version tree.

**Comment by tkeemon** [comment]
I'll have to ask @natea just to be sure, but I don't see any harm in pointing to your theme repo from the staging server.

For production, I think we'd prefer to have the theme come from one of our repos. A bad Mako template can inadvertently take down the entire site. If that happens and we don't have push access on your repo, then we have to clone your repo, make our fix, and redirect the server to our theme anyway. Because we're responsible for the uptime of your production server we want to (1) make sure the site doesn't go down in the first place and (2) make it as easy as possible to fix problems in the event something does break.

**Comment by mbifulco** [comment]
Yeah, in retrospect, that all makes sense - may as well use the same process for both staging and production, in that case.  I'd like to keep this as simple as possible for all parties involved.  

So at the moment, where do we stand?  Are you waiting on anything from me?

**Comment by mbifulco** [comment]
@tkeemon coming back to this - is there a way to use the ansible playbooks in https://github.com/edx/configuration to set up the variables set above?  I'm not sure exactly what happened, but my devstack image essentially reset itself last night, and I lost the changes I made to those variables (theme and such are still intact, just not being used because the theme variable is unset).  I'd like to have a fork of edx/configuration set up so that I can do this again someday, if needed.

**Pull request closed without merging**
