### PR TITLE
Tahoe API - Fixed enrollment so that "unenroll" returns error

### PR DESCRIPTION
**Pull request by johnbaldwin**
This is until we implement "unenroll"

### CODE REVIEW

**Comment by johnbaldwin** [comment]
[(8) Enrollment API PR, fixes](https://trello.com/c/tj4QlCJD/4212-8-enrollment-api-pr-fixes)

**Comment by thraxil** [comment]
@johnbaldwin you might want to rebase this to pull in the pep8 fixes from #422 so TravisCI passes.

**Comment by johnbaldwin** [comment]
@thraxil Thanks! I'll merge it

**Comment by OmarIthawi** [comment]
@johnbaldwin the usual practice is to do a rebase like the following:

```
$ git checkout appsember/tahoe/develop
$ git pull
$ git checkout john/fix-enrollment-api
$ git rebase appsember/tahoe/develop
$ git push --force-with-lease  # Avoids pushing on an updated branch
```


## Long story:
This ensures a cleaner git history when debugging. Git history is very important (to me at least) when finding subtle bugs. I use tools such as `$ git bisect` to do a binary search throughout the git history to spot when a certain bug have got introduced

**Comment by johnbaldwin** [comment]
@OmarIthawi I'll rewind and do that

**Comment by johnbaldwin** [comment]
After rebase, one of the enrollment api tests is failing. Looking into it...

**Comment by johnbaldwin** [comment]
Yep, confirmed, unexpected behavior: A registered learner NOT previously enrolled in a course now shows that the learner *WAS* previously enrolled in the course. Investigating...

**Comment by johnbaldwin** [comment]
@OmarIthawi ready for another review pass if you would please.

I rebased from `appsembler/tahoe/develop`, fixed the rebase conflict _correctly this time_ and did a little flake8 cleanup on the enrollment test and the v1.views module

**Comment by johnbaldwin** [comment]
@OmarIthawi Looks like all checks passed now. Also, I rebased from `..develop` instead of merge. Would you please check it over again?

**Pull request merged**
