### PR TITLE
Merged upstream edx branch "open-release/ficus.master"

### PR DESCRIPTION
**Pull request by johnbaldwin**
Purpose is to bring in the MathJax CDN url fix from upstream into our Ficus develop branch

### CODE REVIEW

**Comment by johnbaldwin** [comment]
[(6) cdn.mathjax.org End of Life](https://trello.com/c/tGM7dLO4/1519-6-cdn-mathjax-org-end-of-life)

**Comment by bezidejni** [comment]
@johnbaldwin Just a note - we don't usually merge the release branch, but a released named version using a tag. So you'd want to use `open-release/ficus.3` instead of `open-release/ficus.master`

**Comment by melvinsoft** [comment]
@johnbaldwin I created a new PR for Ficus, cherry picking the Mathjax fix, so we can merge it faster and with a lower risk: https://github.com/appsembler/edx-platform/pull/118

If you're ok with the new one, I think we can close this one.

**Comment by bezidejni** [comment]
@melvinsoft Isn't merging this a better idea than cherrypicking, since we also pull in other bug fixes?

**Comment by melvinsoft** [comment]
@bezidejni Yes, probably, but since the Mathjax could be a blocker, I thought in cherry pick the commit to make the review/merge process faster.

I'm going to review this PR and close the other one. // cc @johnbaldwin

**Comment by melvinsoft** [comment]
[Mathjax End Of Life Ficus](https://trello.com/c/Ru4JTbd3/1614-mathjax-end-of-life-ficus)

**Pull request merged**
