### PR TITLE
develop -> master

### PR DESCRIPTION
**Pull request by OmarIthawi**
Some fixes including completion!

### TODO

 - [x] Spot checking on staging by Omar.
 - [x] Spot checking on staging by someone else.

### CODE REVIEW

**Comment by johnbaldwin** [comment]
@OmarIthawi How much effort to include the PR numbers in the develop -> master PR descriptions? Or do you think it not worth the effort?

**Comment by OmarIthawi** [comment]
> Have we spot tested this on Tahoe staging?

Not yet.

> @OmarIthawi How much effort to include the PR numbers in the develop -> master PR descriptions? Or do you think it not worth the effort? My thoughts are that if we've reviewed all the PRs that go into the develop -> master and if the develop -> master PR is just an accumulation of those, then it makes the develop -> master PR a sanity check. Do you agree?

I'm not sure of the effort-to-value of such change in the process.

Could you please explain more about how do you think this could be useful?

**Comment by OmarIthawi** [comment]
@melvinsoft I've spot checked the changes on Staging and both looks good. Could you please do one more check so we push it to production early next week?

**Comment by melvinsoft** [comment]
@OmarIthawi Sure, I'll do today. Thanks!

**Comment by melvinsoft** [comment]
@OmarIthawi I just found 1 small error here. In studio -> Files and Uploads when I upload a new file and try to use the "Web" url, is missing the `https` at the beginning.  But I know you discussed about it with John already, so we can follow up later.

**Comment by OmarIthawi** [comment]
> @OmarIthawi I just found 1 small error here. In studio -> Files and Uploads when I upload a new file and try to use the "Web" url, is missing the `https` at the beginning. But I know you discussed about it with John already, so we can follow up later.

Thanks @melvinsoft, yes, it's a known issue. I'd like to hear from itential first before providing any fix.

**Pull request merged**
