### PR TITLE
Revert upstream Hawthorn-specific commits

### PR DESCRIPTION
**Pull request by OmarIthawi**
Following the guide in [Reverting upstream Hawthorn-specific commits](https://appsembler.atlassian.net/wiki/spaces/PM/pages/899678536/How+to+Merge+Juniper+into+Tahoe#Reverting-upstream-Hawthorn-specific-commits) of the Juniper merge how-to guide. 

 - Jira issue: RED-1492

### Detailed steps
I've posted the script that I've used with detailed steps of the revert process in this gist: https://gist.github.com/OmarIthawi/5fdb386c88708a61dd2b94aa6b15ff3a

### TODO
 - [x] Open a decision document on the branches for Tahoe given that we're using them for Enterprise: [[Draft] Decision: Juniper branches naming](https://appsembler.atlassian.net/wiki/spaces/PM/pages/964100251/Draft+Decision+Juniper+branches+naming)
 - [x] Decide on the branch name for `appsembler/juniper-upgrade` [Slack thread](https://appsembler.slack.com/archives/C0DLX9U86/p1602836388120400)
 - [x] Finish the cherry-pick removals according to the [guide](https://appsembler.atlassian.net/wiki/spaces/PM/pages/899678536/How+to+Merge+Juniper+into+Tahoe#Reverting-upstream-Hawthorn-specific-commits)

### How to Review?

It's one of those `fyi` PRs that are hard to review in details. Acknowledging that you've seen the PR and [the script in the gist](https://gist.github.com/OmarIthawi/5fdb386c88708a61dd2b94aa6b15ff3a) is enough.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
I'm almost halfway through the reverting so far. Here's my `revert.sh` script which I use to make this PR:

```sh
set -xe
git reset --hard HEAD

# How to read this script?
#  - Read the How-to Merge Juniper doc: https://appsembler.atlassian.net/wiki/spaces/PM/pages/899678536/How+to+Merge+Juniper+into+Tahoe#Reverting-upstream-Hawthorn-specific-commits
#  - Commented lines (with ##) are successful reverts.
#  - Uncommented lines are pending reverts.
#  - Whenever possible, commits are grouped.
#  - When needed a Jira card is linked.


# ------------

# [ Translation and minor fixes: no action needed ]
## git revert --no-edit f44ac32bc9  # Set the RELEASE_LINE to hawthorn
## git revert --no-edit d81ce02c28  # Hawthorn-specific translations on Transifex
## git revert --no-edit 5fca3847e6  # updated subsection styling to show label on same line as icon, meant to complete EDUCATOR-2535
## git revert --no-edit d3993b8a92  # (tag: open-release/hawthorn.1rc1) updated header active tab border color

# [ Django wiki upgrade: no action needed ]
## git revert --no-edit c6303bc960eb64623b9708fb5a1e43423703da77
## git revert --no-edit d0349d1baeb1a1f9336e8c8bd77167bbbeb347d8
## git revert --no-edit 5d2157587f4b6d0c54903c91487817e0d14fb427

## git revert --no-edit a479aaeacc23e9b6d0e3aedbc137eab87b6a74b7  # CAG edx-search
## git revert --no-edit c19f6bd77b6c9256953f4091d1c002a6a1ccc5e6  # CAG edx-search

# [ Remove CAG support: Action needed RED-1488]
## git revert --no-edit e435809f20  # Bump version of edx-search

# [ S3 boto Tahoe support: Action needed RED-1528 ]
## git revert --no-edit 156dbce36bad303a25385365047e66e8215f0ae8 # Appsembler: update to boto3 in cms
## git revert --no-edit 8077909dd45253f4af5237dad320168f589dadce # Appsembler: update to boto3 in cms
## git revert --no-edit 65db8a5f043587158c6c5895ba9172fb927bc6c8 # Appsembler: update to boto3 in cms
## git revert --no-edit a9ae4c57e5ffcb151e9a59aae9170c20358d5b4f # Appsembler: update to boto3 in cms
## git revert --no-edit 50927efc95469a06c7d7feced1a98ed464f72dd5  # Appsembler: update to boto3 in cms
## git revert --no-edit 1e82b31df8  # Only use export_output_handler if artifact storage is explicitly FileSystemStorage Use StreamingHttpResponse to support larger file downloads


# [ User utils package: no action needed ]
## git revert --no-edit 82d10a0bccf98d91757eea46d9316268f057994f  # extra: for user-util
## git revert --no-edit 0fff03cceb  # bump user-util to 0.1.4

# [ report generation: no action needed ]
## git revert --no-edit facccb96a7  # Add correct answer to response
## git revert --no-edit 9f6fce2b45  # Update report generation code to include old state for backwards compatibility Include report data generated by blocks as columns instead of a json dict

# [ Minor fixes: no action needed ]
## git revert --no-edit df386b6493  # Configure MathJax when it's loaded by XBlocks in studio
## git revert --no-edit c194c7ca09  # Import factories/base.js when using webpack to fix nav
## git revert --no-edit 3ad385303f  # Cherry-pick pr #18639: Escape chemical equation in advanced problems

git revert --no-edit 2814c2f468  # (tag: open-release/hawthorn.1rc3, tag: open-release/hawthorn.1rc2) Upgrade recommender xblock to patch the xss risk
git revert --no-edit 83cf7235a6  # Do not delete course enrollments
git revert --no-edit 3016d2fa3e  # Upgrade Django to 1.11.15
git revert --no-edit 63ce8a7215  # Upgrade Django to 1.11.15 in base.in as well
git revert --no-edit 6249d4c06a  # (tag: open-release/hawthorn.1, upstream/mroytman/remove-waffle-flags-switches) Adds a waffle switch which gates access to the CourseEnrollmentAdmin views
git revert --no-edit 7447baed62  # remove enable_edit_image_modal waffle flag
git revert --no-edit fbf905c161  # Update recommender-xblock version
git revert --no-edit 1107961895  # Bulk rehashing of retired usernames
git revert --no-edit d6ea0e2cc0  # Add forums renaming to bulk username rehash command
git revert --no-edit f9fb87d0de  # Update retirement to handle multiple UserRetirementStatus rows returned
git revert --no-edit 73885529fd  # Stop acct creation from using usernames still in the retirement queue
git revert --no-edit 82d10a0bcc  # Upgrade user-util to 0.1.5
git revert --no-edit c89d08c9cf  # Fix failures due to creating users during initial migrations
git revert --no-edit e524783585  # Update bulk_rehash_retired_usernames
git revert --no-edit 32965363db  # PLAT-2217 - fix partner reporting queue 500 errors, reduce log spam
git revert --no-edit 99a0c368e5  # PLAT-2186 - allow retirement states to be forced by driver script
git revert --no-edit 715b8d31ac  # Adding user_api call to get retirements by date range and current state
git revert --no-edit 313be9b2ab  # Mgmt command to cancel user retirement request.
git revert --no-edit 1a66c1542d  # undo a hand-modification performed as part of a previous cherry-pick
git revert --no-edit 24f6faf5d8  # Bump RecommenderXBlock version
git revert --no-edit 58d2ac8c92  # (tag: open-release/hawthorn.2) Edit test value to be valid URL format
git revert --no-edit 86ad037847  # load cached npm cache on jenkins workers
git revert --no-edit 03b9d89c83  # Convert DATA_DIR to a Path object when fetching from ENV_TOKENS
git revert --no-edit 7ad437b52c  # Fixed override due date by limiting scope to selected users
git revert --no-edit e15db512ed  # Cherry-pick commit changing readthedocs url to https
git revert --no-edit a8ae0f8672  # Bokchoy and quality fixes
git revert --no-edit 213c723911  # add babel-polyfill in commons
git revert --no-edit d6378d47d1  # Use i18n-tools 0.4.6, [CRI-129]
git revert --no-edit 62b715a2a3  # Use XBlock services to get translation at runtime
git revert --no-edit 918cae9cde  # Put certificate data message into it's own block for overriding
git revert --no-edit 25929c02ab  # Clean XSS in lms template
git revert --no-edit 372351e4ff  # Clean Xblock handler
git revert --no-edit e57b542f58  # Clean XSS in Certificates Support URL
git revert --no-edit dfc974d190  # Update django wiki version
git revert --no-edit 22d1b76c3c  # Bump Django version to 1.11.18
git revert --no-edit 368eb3e688  # Read RETIRED_USER_SALTS from the Django settings.
git revert --no-edit 896e66f8fc  # Adds optional args to create_dot_application command
git revert --no-edit dccf61430f  # (upstream/open-release/hawthorn.master, open-release/hawthorn.master) update django wiki version
```

**Comment by OmarIthawi** [comment]
@thraxil fyi

**Comment by OmarIthawi** [comment]
More than halfway through the process:

```sh
set -xe
git reset --hard HEAD

# How to read this script?
#  - Read the How-to Merge Juniper doc: https://appsembler.atlassian.net/wiki/spaces/PM/pages/899678536/How+to+Merge+Juniper+into+Tahoe#Reverting-upstream-Hawthorn-specific-commits
#  - Commented lines (with ##) are successful reverts.
#  - Uncommented lines are pending reverts.
#  - Whenever possible, commits are grouped.
#  - When needed a Jira card is linked.
#
# How to run this script?
#  - Run it `$ bash revert.sh`
#  - Comment out successful reverts
#  - Debug the conflicting revert by looking at file history
#  - A broken revert is fixed by undoing work that has been done _after_ the offending commit (manual process depending on guesswork). 

# ------------

# [ Translation and minor fixes: no action needed ]
## git revert --no-edit f44ac32bc9  # Set the RELEASE_LINE to hawthorn
## git revert --no-edit d81ce02c28  # Hawthorn-specific translations on Transifex
## git revert --no-edit 5fca3847e6  # updated subsection styling to show label on same line as icon, meant to complete EDUCATOR-2535
## git revert --no-edit d3993b8a92  # (tag: open-release/hawthorn.1rc1) updated header active tab border color

# [ Django wiki upgrade: no action needed ]
## git revert --no-edit c6303bc960eb64623b9708fb5a1e43423703da77
## git revert --no-edit d0349d1baeb1a1f9336e8c8bd77167bbbeb347d8
## git revert --no-edit 5d2157587f4b6d0c54903c91487817e0d14fb427

## git revert --no-edit a479aaeacc23e9b6d0e3aedbc137eab87b6a74b7  # CAG edx-search
## git revert --no-edit c19f6bd77b6c9256953f4091d1c002a6a1ccc5e6  # CAG edx-search

# [ Remove CAG support: Action needed RED-1488]
## git revert --no-edit e435809f20  # Bump version of edx-search

# [ S3 boto Tahoe support: Action needed RED-1528 ]
## git revert --no-edit 156dbce36bad303a25385365047e66e8215f0ae8 # Appsembler: update to boto3 in cms
## git revert --no-edit 8077909dd45253f4af5237dad320168f589dadce # Appsembler: update to boto3 in cms
## git revert --no-edit 65db8a5f043587158c6c5895ba9172fb927bc6c8 # Appsembler: update to boto3 in cms
## git revert --no-edit a9ae4c57e5ffcb151e9a59aae9170c20358d5b4f # Appsembler: update to boto3 in cms
## git revert --no-edit 50927efc95469a06c7d7feced1a98ed464f72dd5  # Appsembler: update to boto3 in cms
## git revert --no-edit 1e82b31df8  # Only use export_output_handler if artifact storage is explicitly FileSystemStorage Use StreamingHttpResponse to support larger file downloads


# [ User utils package: no action needed ]
## git revert --no-edit 82d10a0bccf98d91757eea46d9316268f057994f  # extra: for user-util
## git revert --no-edit 0fff03cceb  # bump user-util to 0.1.4

# [ report generation: no action needed ]
## git revert --no-edit facccb96a7  # Add correct answer to response
## git revert --no-edit 9f6fce2b45  # Update report generation code to include old state for backwards compatibility Include report data generated by blocks as columns instead of a json dict

# [ Minor fixes: no action needed ]
## git revert --no-edit df386b6493  # Configure MathJax when it's loaded by XBlocks in studio
## git revert --no-edit c194c7ca09  # Import factories/base.js when using webpack to fix nav
## git revert --no-edit 3ad385303f  # Cherry-pick pr #18639: Escape chemical equation in advanced problems

# [ORA2 by Maxi]
## git revert --no-edit b4645457d9a53263114e88db0e892172ac7d4ad7  # fix ora2 requirement lines
## git revert --no-edit 4ab72f224f0298ee50cc7f20d6e2b6978ab35f8e  # update ORA2 to avoid conflicts with edx-i18n-tools

# [ Recommender XBlock ]
## git revert --no-edit 24f6faf5d8  # Bump RecommenderXBlock version
## git revert --no-edit fbf905c161  # Update recommender-xblock version
## git revert --no-edit 2814c2f468  # (tag: open-release/hawthorn.1rc3, tag: open-release/hawthorn.1rc2) Upgrade recommender xblock to patch the xss risk

## git revert --no-edit 83cf7235a6  # Do not delete course enrollments

# [ Django updgrades ]
## git revert --no-edit 2d230ae99a732a93e91b38f826b831444d2b54b1  # John: Bump Django to 1.11.29
## git revert --no-edit 2bc6ffbd0d9e4a7714c939c33196df1cc7fc8ac3  # Anders: Bump Django to 1.11.23
## git revert --no-edit 3016d2fa3e  # Upgrade Django to 1.11.15
## git revert --no-edit 63ce8a7215  # Upgrade Django to 1.11.15 in base.in as well

## git revert --no-edit 6249d4c06a  # (tag: open-release/hawthorn.1, upstream/mroytman/remove-waffle-flags-switches) Adds a waffle switch which gates access to the CourseEnrollmentAdmin views
## git revert --no-edit 7447baed62  # remove enable_edit_image_modal waffle flag


## git revert --no-edit 1a66c1542d  # undo a hand-modification performed as part of a previous cherry-pick
## git revert --no-edit e524783585  # Update bulk_rehash_retired_usernames
## git revert --no-edit d6ea0e2cc0  # Add forums renaming to bulk username rehash command
## git revert --no-edit 1107961895  # Bulk rehashing of retired usernames
returned

git revert --no-edit f9fb87d0de  # Update retirement to handle multiple UserRetirementStatus rows


git revert --no-edit 73885529fd  # Stop acct creation from using usernames still in the retirement queue
git revert --no-edit 82d10a0bcc  # Upgrade user-util to 0.1.5
git revert --no-edit c89d08c9cf  # Fix failures due to creating users during initial migrations
git revert --no-edit 32965363db  # PLAT-2217 - fix partner reporting queue 500 errors, reduce log spam
git revert --no-edit 99a0c368e5  # PLAT-2186 - allow retirement states to be forced by driver script
git revert --no-edit 715b8d31ac  # Adding user_api call to get retirements by date range and current state
git revert --no-edit 313be9b2ab  # Mgmt command to cancel user retirement request.
git revert --no-edit 58d2ac8c92  # (tag: open-release/hawthorn.2) Edit test value to be valid URL format
git revert --no-edit 86ad037847  # load cached npm cache on jenkins workers
git revert --no-edit 03b9d89c83  # Convert DATA_DIR to a Path object when fetching from ENV_TOKENS
git revert --no-edit 7ad437b52c  # Fixed override due date by limiting scope to selected users
git revert --no-edit e15db512ed  # Cherry-pick commit changing readthedocs url to https
git revert --no-edit a8ae0f8672  # Bokchoy and quality fixes
git revert --no-edit 213c723911  # add babel-polyfill in commons
git revert --no-edit d6378d47d1  # Use i18n-tools 0.4.6, [CRI-129]
git revert --no-edit 62b715a2a3  # Use XBlock services to get translation at runtime
git revert --no-edit 918cae9cde  # Put certificate data message into it's own block for overriding
git revert --no-edit 25929c02ab  # Clean XSS in lms template
git revert --no-edit 372351e4ff  # Clean Xblock handler
git revert --no-edit e57b542f58  # Clean XSS in Certificates Support URL
git revert --no-edit dfc974d190  # Update django wiki version
git revert --no-edit 22d1b76c3c  # Bump Django version to 1.11.18
git revert --no-edit 368eb3e688  # Read RETIRED_USER_SALTS from the Django settings.
git revert --no-edit 896e66f8fc  # Adds optional args to create_dot_application command
git revert --no-edit dccf61430f  # (upstream/open-release/hawthorn.master, open-release/hawthorn.master) update django wiki version
```

**Comment by OmarIthawi** [comment]
This branch is mostly now ready to be merged. I've gone through all the commits, not every commit was reverted though, which is normal.

```sh
set -xe
git reset --hard HEAD

# How to read this script?
#  - Read the How-to Merge Juniper doc: https://appsembler.atlassian.net/wiki/spaces/PM/pages/899678536/How+to+Merge+Juniper+into+Tahoe#Reverting-upstream-Hawthorn-specific-commits
#  - Commented lines (with ##) are successful reverts
#  - Uncommented lines are pending reverts
#  - Whenever possible, commits are grouped with "[ section title ]"
#  - When needed a Jira card is linked
#  - Unsuccessful lines are prefixed with `NOT REVERTED` with an explaination on the line below
#
# How to run this script?
#  - Run it `$ bash revert.sh`
#  - Comment out successful reverts
#  - Debug the conflicting revert by looking at file history
#  - A broken revert is fixed by undoing work that has been done _after_ the offending commit (manual process depending on guesswork).

# ------------

# [ Translation and minor fixes: no action needed ]
## git revert --no-edit f44ac32bc9  # Set the RELEASE_LINE to hawthorn
## git revert --no-edit d81ce02c28  # Hawthorn-specific translations on Transifex
## git revert --no-edit 5fca3847e6  # updated subsection styling to show label on same line as icon, meant to complete EDUCATOR-2535
## git revert --no-edit d3993b8a92  # (tag: open-release/hawthorn.1rc1) updated header active tab border color

# [ Django wiki upgrade: no action needed ]
## git revert --no-edit c6303bc960eb64623b9708fb5a1e43423703da77
## git revert --no-edit d0349d1baeb1a1f9336e8c8bd77167bbbeb347d8
## git revert --no-edit 5d2157587f4b6d0c54903c91487817e0d14fb427
## NOT REVERTED: c6303bc960eb64623b9708fb5a1e43423703da77  # Updated Django wiki version
##    ^^^ already reverted above
## NOT REVERTED: dccf61430f  # (upstream/open-release/hawthorn.master, open-release/hawthorn.master) update django wiki version
##    ^^^ already reverted above

## git revert --no-edit a479aaeacc23e9b6d0e3aedbc137eab87b6a74b7  # CAG edx-search
## git revert --no-edit c19f6bd77b6c9256953f4091d1c002a6a1ccc5e6  # CAG edx-search

# [ Remove CAG support: Action needed RED-1488]
## git revert --no-edit e435809f20  # Bump version of edx-search

# [ S3 boto Tahoe support: Action needed RED-1528 ]
## git revert --no-edit 156dbce36bad303a25385365047e66e8215f0ae8 # Appsembler: update to boto3 in cms
## git revert --no-edit 8077909dd45253f4af5237dad320168f589dadce # Appsembler: update to boto3 in cms
## git revert --no-edit 65db8a5f043587158c6c5895ba9172fb927bc6c8 # Appsembler: update to boto3 in cms
## git revert --no-edit a9ae4c57e5ffcb151e9a59aae9170c20358d5b4f # Appsembler: update to boto3 in cms
## git revert --no-edit 50927efc95469a06c7d7feced1a98ed464f72dd5  # Appsembler: update to boto3 in cms
## git revert --no-edit 1e82b31df8  # Only use export_output_handler if artifact storage is explicitly FileSystemStorage Use StreamingHttpResponse to support larger file downloads


# [ User utils package: no action needed ]
## git revert --no-edit 82d10a0bcc  # Upgrade user-util to 0.1.5
## git revert --no-edit 0fff03cceb  # bump user-util to 0.1.4

# [ report generation: no action needed ]
## git revert --no-edit facccb96a7  # Add correct answer to response
## git revert --no-edit 9f6fce2b45  # Update report generation code to include old state for backwards compatibility Include report data generated by blocks as columns instead of a json dict

# [ Minor fixes: no action needed ]
## git revert --no-edit df386b6493  # Configure MathJax when it's loaded by XBlocks in studio
## git revert --no-edit c194c7ca09  # Import factories/base.js when using webpack to fix nav
## NOT REVERTED: 3ad385303f: Cherry-pick pr #18639: Escape chemical equation in advanced problems
#           ^^^ tests were broken when reverted

# [ORA2 by Maxi]
## git revert --no-edit b4645457d9a53263114e88db0e892172ac7d4ad7  # fix ora2 requirement lines
## git revert --no-edit 4ab72f224f0298ee50cc7f20d6e2b6978ab35f8e  # update ORA2 to avoid conflicts with edx-i18n-tools

# [ Recommender XBlock ]
## git revert --no-edit 24f6faf5d8  # Bump RecommenderXBlock version
## git revert --no-edit fbf905c161  # Update recommender-xblock version
## git revert --no-edit 2814c2f468  # (tag: open-release/hawthorn.1rc3, tag: open-release/hawthorn.1rc2) Upgrade recommender xblock to patch the xss risk

## git revert --no-edit 83cf7235a6  # Do not delete course enrollments

# [ Django updgrades ]
## git revert --no-edit 2d230ae99a732a93e91b38f826b831444d2b54b1  # John: Bump Django to 1.11.29
## git revert --no-edit 2bc6ffbd0d9e4a7714c939c33196df1cc7fc8ac3  # Anders: Bump Django to 1.11.23
## git revert --no-edit 3016d2fa3e  # Upgrade Django to 1.11.15
## git revert --no-edit 63ce8a7215  # Upgrade Django to 1.11.15 in base.in as well

## git revert --no-edit 6249d4c06a  # (tag: open-release/hawthorn.1, upstream/mroytman/remove-waffle-flags-switches) Adds a waffle switch which gates access to the CourseEnrollmentAdmin views
## git revert --no-edit 7447baed62  # remove enable_edit_image_modal waffle flag


## git revert --no-edit 1a66c1542d  # undo a hand-modification performed as part of a previous cherry-pick
## git revert --no-edit e524783585  # Update bulk_rehash_retired_usernames
## git revert --no-edit d6ea0e2cc0  # Add forums renaming to bulk username rehash command
## git revert --no-edit 1107961895  # Bulk rehashing of retired usernames returned


# [ Retirement view and MTE emails ]
## Related: c86f4ad83c680231b939db7331ec7e3694ea9882  # Fix RED-1212: Retirement not working due to hack suffix
## NOT REVERTED: f9fb87d0de: Update retirement to handle multiple UserRetirementStatus rows
##    ^^^ too many conflicts were found, likely to have less conflicts when merging upstream

## NOT REVERTED: 73885529fd  # Stop acct creation from using usernames still in the retirement queue
##    ^^^ too many conflicts were found, likely to have less conflicts when merging upstream
## NOT REVERTED: c89d08c9cf  # Fix failures due to creating users during initial migrations
##    ^^^ too many conflicts were found, likely to have less conflicts when merging upstream
## NOT REVERTED git revert --no-edit 715b8d31ac  # Adding user_api call to get retirements by date range and current state
##    ^^^ too many conflicts were found, likely to have less conflicts when merging upstream

## git revert --no-edit 32965363db  # PLAT-2217 - fix partner reporting queue 500 errors, reduce log spam

## git revert --no-edit 99a0c368e5  # PLAT-2186 - allow retirement states to be forced by driver script

## git revert --no-edit 313be9b2ab  # Mgmt command to cancel user retirement request.
## git revert --no-edit 58d2ac8c92  # (tag: open-release/hawthorn.2) Edit test value to be valid URL format
## git revert --no-edit 86ad037847  # load cached npm cache on jenkins workers
## git revert --no-edit 03b9d89c83  # Convert DATA_DIR to a Path object when fetching from ENV_TOKENS
## git revert --no-edit 7ad437b52c  # Fixed override due date by limiting scope to selected users

## NOT REVERTED: e15db512ed  # Cherry-pick commit changing readthedocs url to https
##   ^^^^ The commit didn't show up in the history
## NOT REVERTED: a8ae0f8672  # Bokchoy and quality fixes
##    ^^^ too many conflicts were found, likely to have less conflicts when merging upstream
## NOT REVERTED: 62b715a2a3  # Use XBlock services to get translation at runtime
#   ^^^^ I chose to ignore it. It seems that it doesn't need a revert
## NOT REVERTED: d6378d47d1  # Use i18n-tools 0.4.6, [CRI-129]
#   ^^^^ I chose to ignore it. It seems that it doesn't need a revert

## [ Set of commits that did not get reverted: the revert commits didn't show up in history ]
## NOT REVERTED: 918cae9cde  # Put certificate data message into it's own block for overriding
## NOT REVERTED: 25929c02ab  # Clean XSS in lms template
## NOT REVERTED: 372351e4ff  # Clean Xblock handler
## NOT REVERTED: e57b542f58  # Clean XSS in Certificates Support URL
## NOT REVERTED: dfc974d190  # Update django wiki version
## NOT REVERTED: 22d1b76c3c  # Bump Django version to 1.11.18
## NOT REVERTED: 368eb3e688  # Read RETIRED_USER_SALTS from the Django settings.
## NOT REVERTED: 896e66f8fc  # Adds optional args to create_dot_application command
## NOT REVERTED: 213c723911  # add babel-polyfill in commons
```

**Review by thraxil — APPROVED** [review]

**Pull request merged**
