### PR TITLE
Use tahoe-idp 2.4.0

### PR DESCRIPTION
**Pull request by bryanlandia**
## Change description

Adds feature to sync configured user fields (default first, last, full names) back to IdP on User and UserProfile post_save.  Signal handlers configured via plugin arch

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

https://appsembler.atlassian.net/browse/ENG-125

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

### CODE REVIEW

**Comment by bryanlandia** [comment]
Back to draft... haven't actually released 2.4.0 to PyPI yet :D

**Comment by bryanlandia** [comment]
Putting back ready to review, just expect the Build test will fail until 1.4.0 is cut
See https://github.com/appsembler/tahoe-idp/pull/87

**Review by amirtds — APPROVED** [review]

**Comment by bryanlandia** [comment]
Closed in favor of #1348

**Comment by bryanlandia** [comment]
Closing to use 2.4.3

**Pull request closed without merging**
