### PR TITLE
add usage features with django-souvenirs

### PR DESCRIPTION
**Pull request by agriffis**
This pull request adds two related features to appsembler's fork of edx-platform:

* measurement of user activity
* aggregation of user activity to a central data store for reporting

These features can be selectively enabled in production via independent flags in `APPSEMBLER_FEATURES`

## measurement

The measurement part of this pull request depends on [django-souvenirs](https://github.com/appsembler/django-souvenirs) and enables the middleware in `envs/aws_appsembler.py` depending on the feature flag `ENABLE_USAGE_TRACKING`

After enabling souvenirs, the management command `show_usage` becomes available.

## aggregation

The aggregation part of this pull request depends on [psycopg2](https://pypi.python.org/pypi/psycopg2) and adds the `appsembler_usage` django app depending on the feature flag `ENABLE_USAGE_AGGREGATION`. It adds the following management commands:

* `email_usage` is similar to souvenir's `show_usage` but... sends email
* `backfill_usage` reads a directory of tracking logs to fill the souvenirs table
* `aggregate_usage` runs some reports similar to `show_usage` and populates the results into the aggregation database rather than to the screen

The really notable part about the aggregation is the shared google cloud sql (postgresql 9.6) database. Each instance of open edx is assigned its own postgres user in the boxes role. Because of row-level security policies, that user is only able to access the table rows with a matching `customer_id`. In this way a compromised box can't be used to access cross-customer data.

However because each instance gets its own DB credentials, database-level operations such as migrations need to be performed using the privileged "postgres" user. The operator can accomplish this on any box (including an appropriately-configured devstack) by setting `APPSEMBLER_USAGE_DB_AUTH=postgres:XXX` in the environment before running migrations.

Note that nothing in the `appsembler_usage` app runs during the request/response cycle, rather it's entirely contained in the management commands (some of which are intended to run from cron). So even though this app adds the dependency on an external database with "interesting" credentials, enabling the `ENABLE_USAGE_AGGREGATION` flag should have no effect on normal lms/cms operation.

There's more nuts-and-bolts information in [deployment.txt](https://drive.google.com/file/d/0B4MlukKoQZN1X3E0LUlEdUROT1E/view) and some additonal cleanup stuff in [ops-todo.txt](https://drive.google.com/file/d/0B4MlukKoQZN1NG5MZTRsNWphUlU/view)

## tests

This PR doesn't add new tests to edx-platform. Rather my strategy was to push as much of the code into django-souvenirs as possible, which has almost 100% coverage.

This means that the `aggregate_usage` and `backfill_usage` management commands don't have test coverage. Since they're management commands rather than user-facing functionality, I think this is probably okay for now and doesn't add significant technical debt. If testing them explicitly is desired in the future, it would involve (1) adding `DATABASES['appsembler_usage']` to the test settings, (2) conditionalizing the migrations that depend on PostgreSQL DDL (if migrations run at all during testing).

## examples

running the backfill script (to fill souvenirs DB from tracking logs)

```
$ ./manage.py lms --settings=aws_appsembler backfill_usage
processed 735433 lines:
  13978 added
      8 duplicated
 450505 ignored (no user id)
 270942 rate-limited
```

checking the usage over time

```
$ ./manage.py lms --settings=aws_appsembler show_usage --subscription-start=2016-08-04
date          registered    activated    active
----------  ------------  -----------  --------
2016-09-04            12            8         0
2016-10-04            13            9         0
2016-11-04            13            9         0
2016-12-04            13            9         0
2017-01-04           752          596         0
2017-02-04          1640         1318         0
2017-03-04          2156         1752       483
2017-03-16          2369         1924       541
TOTAL               2370         1925       829
```

aggregating to cloud sql

```
$ time ./manage.py lms --settings=aws_appsembler aggregate_usage \
        --customer-id=example__example \
        --customer-name="Example" \
        --subscription-start=1/1/2016 \
        --quota=1000
updated 0 rows
added 498 rows

real    2m41.817s
user    0m9.865s
sys     0m0.700s
```

### CODE REVIEW

**Comment by bezidejni** [comment]
@agriffis I didn't have the time to go into details too much, but the only thing that I'd definitely change is to move the app from `common/djangoapps/appsembler_usage` to `openedx/core/djangoapps/appsembler/usage`. It seems like the edX people are moving all the apps to that folder, and there's an added benefit of having an appsembler namespace (which we're already doing) so the actual app doesn't have to be prefixed with `appsembler_`.

Otherwise it looks really good. 👍

**Comment by agriffis** [comment]
@bezidejni I moved it to `openedx/core/djangoapps/appsembler/appsembler_usage` which is a bit redundant and not quite what you suggested, but avoids needing to change the app label which is already encoded in migrations that have run on the production cloud SQL. Also I'm not sure that "usage" is quite unique enough as an app label on its own. Thanks!

**Comment by agriffis** [comment]
@bezidejni Actually I went ahead and moved it to `openedx/core/djangoapps/appsembler/usage` as you suggested, but I added a custom `AppConfig` to set the app label to `appsembler_usage` so everything continues working.

**Comment by bezidejni** [comment]
@agriffis Thanks, good call!

**Comment by melvinsoft** [comment]
[(4) Install the Scampersand reporting app on Eucalyptus customer servers](https://trello.com/c/G31rBXND/1527-4-install-the-scampersand-reporting-app-on-eucalyptus-customer-servers)

**Comment by melvinsoft** [comment]
[Merge Scampersand code into our Ficus branch.](https://trello.com/c/5YxKwuVz/1568-merge-scampersand-code-into-our-ficus-branch)

**Pull request merged**
