### PR TITLE
The usual develop into master merge

### PR DESCRIPTION
**Pull request by melvinsoft**

### CODE REVIEW

**Comment by johnbaldwin** [comment]
@melvinsoft Has Omar's MTE been well tested on staging? http://github.com/appsembler/edx-platform/pull/654

**Comment by melvinsoft** [comment]
@johnbaldwin We're still in the process, but all MTE code are behind a feature flag, and it's currently disabled on production. So in theory MTE should no affect prod until we enable it.

**Comment by OmarIthawi** [comment]
@johnbaldwin @melvinsoft that's correct there's a minor risk that it would break something on production but the risk is negligible because we can revert the code change and it would go back to normal.

All the major changes are both tested on staging and held back with a feature flag.

**Comment by johnbaldwin** [comment]
How stringent do we want to be about doing direct commits to develop versus having everything come in via PR?

**Comment by johnbaldwin** [comment]
Thanks Maxi. Before we enable the feature flag in prod, I believe we should test enabling then disabling the flag on staging, if that testing has not already been done

**Comment by melvinsoft** [comment]
@johnbaldwin We're currently in the Manual Testing / Bugfixing phase of MTE in staging. Yeah, we can test that, but honestly, after enabling this on production and start allowing users to register with the same email in more than 1 Tahoe site, there is now easy way back. The feature flag responds to Omar's development strategy to be able to push changes in small batches to prod, instead of pushing all at once.

**Comment by OmarIthawi** [comment]
> @johnbaldwin We're currently in the Manual Testing / Bugfixing phase of MTE in staging. Yeah, we can test that, but honestly, after enabling this on production and start allowing users to register with the same email in more than 1 Tahoe site, there is now easy way back. The feature flag responds to Omar's development strategy to be able to push changes in small batches to prod, instead of pushing all at once.

@melvinsoft suppose something went really wrong with MTE on production and we wanted to reverse all changes. Here's what we should do:

 - Quickly run the fake migrations `lms ./manage.py lms migrate database_unfixups zero --fake` so we can enable the feature again in the future
 - Quickly shut off the feature flag on production and deploy. This will prevent _adding new_ duplicate emails.
 - Identify users with duplicate emails, change the newer ones to something we own like: 
 `omar@example.com` -> `support+omar_at_example_dot_com@appsembler.com`
 - Reach out to those learners and ask for an alternative email, it could be just `omar+2@example.com`
 - Manually get back the unique constraint

**Comment by melvinsoft** [comment]
@OmarIthawi That's awesome! Thanks for writing a Runbook with the steps.

**Pull request merged**
